// Part 2: Purchase, Suppliers, Customers, Expenses, Reports, Subscription, Settings, Profile test cases

import type { TestCaseDef } from './seed-rm-data-part1';

export const TEST_CASES_PART2: TestCaseDef[] = [
  // ─── PURCHASE (20) ─────────────────────────────────────────────────────
  {
    title: 'Create purchase order with multiple products',
    module: 'Purchase',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Supplier "Raj Traders" exists. Products with GST configured.',
    tags: ['smoke', 'regression', 'purchase', 'po'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > New Purchase Order', expected_result: 'PO creation form opens' },
      { description: 'Select supplier: Raj Traders, add 3 products with quantities and rates', expected_result: 'Line items added with subtotals and GST' },
      { description: 'Set expected delivery date: 7 days from today', expected_result: 'Date accepted' },
      { description: 'Save PO', expected_result: 'PO created with unique PO number. Status: Ordered.' },
    ],
  },
  {
    title: 'Receive goods against purchase order (GRN)',
    module: 'Purchase',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'PO in Ordered status exists.',
    tags: ['smoke', 'regression', 'purchase', 'grn'],
    is_regression: true,
    steps: [
      { description: 'Open PO and tap "Receive Goods"', expected_result: 'GRN form shows expected quantities' },
      { description: 'Enter received quantities (may differ from ordered)', expected_result: 'Quantities updated' },
      { description: 'Save GRN', expected_result: 'Stock increases per received quantities. PO status → Received. Supplier payable recorded.' },
    ],
  },
  {
    title: 'Partial goods receipt updates PO status to Partially Received',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'PO for 100 units exists.',
    tags: ['purchase', 'grn', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create GRN for only 60 of 100 ordered units', expected_result: 'Stock increases by 60. PO status → Partially Received. Remaining: 40 units.' },
    ],
  },
  {
    title: 'Record supplier payment against outstanding payable',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Supplier has outstanding payable of ₹15,000.',
    tags: ['purchase', 'payment', 'supplier', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > Pay Supplier, select supplier and amount ₹10,000', expected_result: 'Payment form ready' },
      { description: 'Save payment', expected_result: 'Outstanding reduces to ₹5,000. Payment entry created in supplier ledger.' },
    ],
  },
  {
    title: 'Purchase return reduces stock and supplier payable',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'GRN exists with received items.',
    tags: ['purchase', 'return', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > Return, select GRN, enter 10 units to return', expected_result: 'Return form populated' },
      { description: 'Save purchase return', expected_result: 'Stock reduced by 10. Supplier payable reduced by return value.' },
    ],
  },
  {
    title: 'Purchase order cannot be created without supplier',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'PO creation form open.',
    tags: ['purchase', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Leave supplier field blank and try to save PO', expected_result: 'Validation error: "Supplier is required"' },
    ],
  },
  {
    title: 'Purchase order with zero quantity line item is rejected',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'PO form with product added.',
    tags: ['purchase', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Set product quantity to 0 in PO line item', expected_result: 'Error: "Quantity must be at least 1"' },
    ],
  },
  {
    title: 'Purchase report shows total purchase value for date range',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple GRNs exist this month.',
    tags: ['purchase', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > Report, set date to current month', expected_result: 'Report shows all GRNs and total purchase value' },
      { description: 'Verify total matches sum of all GRNs in range', expected_result: 'Values match' },
    ],
  },
  {
    title: 'Cancel purchase order before GRN marks it as cancelled',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'PO in Ordered status.',
    tags: ['purchase', 'cancel'],
    is_regression: false,
    steps: [
      { description: 'Open PO and tap "Cancel Order"', expected_result: 'Confirmation dialog shown' },
      { description: 'Confirm cancellation', expected_result: 'PO status → Cancelled. Stock unchanged. Cannot receive goods against cancelled PO.' },
    ],
  },
  {
    title: 'GST input tax credit correctly shown in purchase invoice',
    module: 'Purchase',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'GST registered business.',
    tags: ['purchase', 'gst', 'itc', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create purchase of product ₹1,000 + 18% GST from registered supplier', expected_result: 'Purchase invoice shows CGST ₹90, SGST ₹90, Total ₹1,180' },
      { description: 'Check GST report for ITC', expected_result: 'Input Tax Credit of ₹180 recorded for GSTR-2 filing' },
    ],
  },
  {
    title: 'Purchase overdue reminder shows in notifications',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Supplier payment due date passed with outstanding balance.',
    tags: ['purchase', 'notifications', 'payment'],
    is_regression: false,
    steps: [
      { description: 'Check notification center', expected_result: 'Notification: "Payment overdue to [Supplier Name] – ₹X outstanding since [date]"' },
    ],
  },
  {
    title: 'Reorder suggestions shown for products below reorder level',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple products below reorder level.',
    tags: ['purchase', 'reorder', 'inventory', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > Reorder Suggestions', expected_result: 'List shows products below reorder level with suggested quantity and preferred supplier' },
      { description: 'Tap "Create PO" from suggestion', expected_result: 'PO pre-filled with suggested products, quantities, and supplier' },
    ],
  },
  {
    title: 'Purchase invoice with supplier GST number validates GSTIN format',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier edit form open.',
    tags: ['purchase', 'gst', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Enter GSTIN: INVALID123', expected_result: 'Validation error: "Invalid GSTIN format. Must be 15 characters."' },
      { description: 'Enter valid GSTIN: 29ABCDE1234F1Z5', expected_result: 'GSTIN accepted and saved' },
    ],
  },
  {
    title: 'GRN date cannot be before PO creation date',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'PO created on today\'s date.',
    tags: ['purchase', 'grn', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Try to set GRN date to yesterday (before PO date)', expected_result: 'Validation error: "GRN date cannot be before Purchase Order date"' },
    ],
  },
  {
    title: 'Purchase against non-existent supplier is blocked',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'PO creation form.',
    tags: ['purchase', 'negative', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Type a supplier name that does not exist in system', expected_result: 'Autocomplete shows no results. Cannot proceed without selecting existing supplier or creating new one.' },
    ],
  },
  {
    title: 'Purchase order PDF can be emailed to supplier',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'PO created. Supplier has email address.',
    tags: ['purchase', 'email', 'pdf'],
    is_regression: false,
    steps: [
      { description: 'Open PO and tap "Send to Supplier"', expected_result: 'Email compose screen opens with PDF attached and supplier email pre-filled' },
      { description: 'Send email', expected_result: 'Email sent. PO status shows "Sent to Supplier".' },
    ],
  },
  {
    title: 'Multiple GRNs against single PO are tracked cumulatively',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'PO for 100 units. First GRN received 40 units.',
    tags: ['purchase', 'grn', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create second GRN for remaining 60 units against same PO', expected_result: 'Second GRN created. Total received = 100/100. PO status → Fully Received.' },
    ],
  },
  {
    title: 'Purchase list search by PO number finds correct order',
    module: 'Purchase',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'PO-2025-0023 exists.',
    tags: ['purchase', 'search'],
    is_regression: false,
    steps: [
      { description: 'Search "PO-2025-0023" in Purchase list', expected_result: 'Exact PO appears in results' },
    ],
  },
  {
    title: 'Network failure during GRN does not partially update stock',
    module: 'Purchase',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'GRN form filled, about to save.',
    tags: ['purchase', 'negative', 'network', 'data-integrity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap Save GRN and immediately disconnect network', expected_result: 'GRN save fails gracefully' },
      { description: 'Reconnect and retry', expected_result: 'GRN saves exactly once. Stock updated exactly once. No partial update.' },
    ],
  },
  {
    title: 'Purchase value report matches supplier ledger totals',
    module: 'Purchase',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Multiple purchases from same supplier.',
    tags: ['purchase', 'reports', 'supplier', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Run Purchase Value Report for supplier "Raj Traders" for this month', expected_result: 'Total purchase amount matches sum of entries in supplier ledger' },
    ],
  },

  // ─── SUPPLIERS (15) ────────────────────────────────────────────────────
  {
    title: 'Add new supplier with complete profile',
    module: 'Suppliers',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'User logged in with Supplier access.',
    tags: ['smoke', 'regression', 'suppliers', 'add'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Suppliers > Add Supplier', expected_result: 'Supplier form opens' },
      { description: 'Enter: Name: Sharma Wholesale, Phone: 9876543210, Email: sharma@wholesale.com, GSTIN: 29ABCDE1234F1Z5, Credit Terms: 30 days', expected_result: 'All fields accept input' },
      { description: 'Save supplier', expected_result: 'Supplier created and visible in list' },
    ],
  },
  {
    title: 'Supplier ledger shows all transactions chronologically',
    module: 'Suppliers',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Supplier with multiple purchases and payments.',
    tags: ['suppliers', 'ledger', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Supplier > Ledger tab', expected_result: 'Chronological list: Purchase invoices (debit), Payments (credit), Running balance' },
    ],
  },
  {
    title: 'Duplicate supplier phone number shows warning',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier with phone 9876543210 exists.',
    tags: ['suppliers', 'validation', 'negative', 'duplicate'],
    is_regression: false,
    steps: [
      { description: 'Add new supplier with same phone number 9876543210', expected_result: 'Warning: "Phone number already registered to [Supplier Name]". Allow override with confirmation.' },
    ],
  },
  {
    title: 'Supplier outstanding balance is correct',
    module: 'Suppliers',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Supplier with purchase ₹10,000 and payment ₹4,000 recorded.',
    tags: ['suppliers', 'payable', 'regression'],
    is_regression: true,
    steps: [
      { description: 'View supplier profile outstanding balance', expected_result: 'Outstanding balance shows ₹6,000 (10,000 - 4,000)' },
    ],
  },
  {
    title: 'Delete supplier with outstanding balance is blocked',
    module: 'Suppliers',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier with outstanding payable > 0.',
    tags: ['suppliers', 'delete', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt to delete supplier with outstanding balance', expected_result: 'Error: "Cannot delete supplier with outstanding balance. Settle accounts first."' },
    ],
  },
  {
    title: 'Supplier purchase history shows all POs and GRNs',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Supplier with multiple transactions.',
    tags: ['suppliers', 'history', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Supplier > Purchase History tab', expected_result: 'List shows all POs and GRNs sorted by date with amounts' },
    ],
  },
  {
    title: 'Supplier search by name returns partial matches',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Multiple suppliers exist.',
    tags: ['suppliers', 'search'],
    is_regression: false,
    steps: [
      { description: 'Search "sharma" in suppliers list', expected_result: 'All suppliers with "sharma" in name shown (case-insensitive)' },
    ],
  },
  {
    title: 'Supplier credit terms affect payment due date calculation',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Supplier credit terms set to 30 days.',
    tags: ['suppliers', 'credit-terms', 'purchase'],
    is_regression: false,
    steps: [
      { description: 'Create purchase on 1st of month from supplier with 30-day credit', expected_result: 'Payment due date auto-calculated as 30th of same month' },
    ],
  },
  {
    title: 'Supplier statement report is accurate',
    module: 'Suppliers',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Supplier with transactions in selected date range.',
    tags: ['suppliers', 'reports', 'statement', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Generate supplier statement for last month', expected_result: 'PDF/screen shows: Opening balance, all purchases, all payments, closing balance' },
      { description: 'Verify: Closing = Opening + Purchases − Payments', expected_result: 'Calculation is accurate' },
    ],
  },
  {
    title: 'Supplier contact details can be updated',
    module: 'Suppliers',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier exists.',
    tags: ['suppliers', 'edit'],
    is_regression: false,
    steps: [
      { description: 'Edit supplier and change phone number', expected_result: 'New phone number saved and visible in supplier profile' },
    ],
  },
  {
    title: 'Supplier without GSTIN can still have purchases recorded',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Unregistered supplier (no GSTIN) exists.',
    tags: ['suppliers', 'gst', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Create purchase from unregistered supplier', expected_result: 'Purchase saved. GST ITC not claimable for this purchase (system shows warning).' },
    ],
  },
  {
    title: 'Export supplier list to CSV',
    module: 'Suppliers',
    priority: 'low',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Suppliers exist.',
    tags: ['suppliers', 'export'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Suppliers > Export', expected_result: 'CSV with Name, Phone, Email, GSTIN, Outstanding Balance downloaded' },
    ],
  },
  {
    title: 'Inactive supplier cannot be selected for new PO',
    module: 'Suppliers',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier marked as Inactive.',
    tags: ['suppliers', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open new PO and search for inactive supplier', expected_result: 'Inactive supplier not shown in search results' },
    ],
  },
  {
    title: 'Supplier top products report shows most purchased items',
    module: 'Suppliers',
    priority: 'low',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple purchases from same supplier.',
    tags: ['suppliers', 'analytics', 'reports'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Supplier > Analytics tab', expected_result: 'Bar chart shows top 5 most purchased products from this supplier by value' },
    ],
  },
  {
    title: 'Supplier name is mandatory field',
    module: 'Suppliers',
    priority: 'high',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'Add Supplier form open.',
    tags: ['suppliers', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Leave name blank and try to save supplier', expected_result: 'Error: "Supplier name is required"' },
    ],
  },

  // ─── CUSTOMERS (15) ────────────────────────────────────────────────────
  {
    title: 'Add new customer with complete profile',
    module: 'Customers',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'User logged in.',
    tags: ['smoke', 'regression', 'customers', 'add'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Customers > Add Customer', expected_result: 'Customer form opens' },
      { description: 'Enter: Name: Meena Devi, Phone: 9988776655, Email: meena@example.com, Address: 12 MG Road Bangalore, Credit Limit: 5000', expected_result: 'All fields accept input' },
      { description: 'Save customer', expected_result: 'Customer created and visible in list' },
    ],
  },
  {
    title: 'Customer outstanding balance is tracked correctly',
    module: 'Customers',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer with credit sales ₹3,000 and payment received ₹1,000.',
    tags: ['customers', 'credit', 'regression'],
    is_regression: true,
    steps: [
      { description: 'View customer profile', expected_result: 'Outstanding balance shows ₹2,000 (3000 - 1000)' },
    ],
  },
  {
    title: 'Record customer payment against outstanding',
    module: 'Customers',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer has outstanding ₹2,000.',
    tags: ['customers', 'payment', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open customer > tap "Receive Payment" > enter ₹1,000', expected_result: 'Payment form ready' },
      { description: 'Save payment', expected_result: 'Outstanding reduces to ₹1,000. Payment entry in ledger.' },
    ],
  },
  {
    title: 'Customer purchase history shows all invoices',
    module: 'Customers',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Customer with multiple sales.',
    tags: ['customers', 'history', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Customer > Purchase History', expected_result: 'All invoices linked to this customer shown with date, amount, status' },
    ],
  },
  {
    title: 'Duplicate phone number shows warning when adding customer',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Customer with phone 9988776655 exists.',
    tags: ['customers', 'validation', 'negative', 'duplicate'],
    is_regression: false,
    steps: [
      { description: 'Add customer with phone 9988776655', expected_result: 'Warning: "Phone already linked to [Customer Name]". Option to link or create new.' },
    ],
  },
  {
    title: 'Customer credit limit prevents exceeding sales on credit',
    module: 'Customers',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer credit limit ₹2,000. Outstanding ₹1,800.',
    tags: ['customers', 'credit', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt credit sale of ₹500 for this customer', expected_result: 'Warning shown: exceeds credit limit. Manager override required.' },
    ],
  },
  {
    title: 'Customer loyalty points accumulate across purchases',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Loyalty: 1 point per ₹10. Customer has 50 points.',
    tags: ['customers', 'loyalty', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Complete ₹200 sale for customer', expected_result: 'Customer earns 20 more points. Total: 70 points shown in profile.' },
    ],
  },
  {
    title: 'Redeem loyalty points on sale reduces invoice total',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Customer has 100 points. Redemption rate: 1 point = ₹1.',
    tags: ['customers', 'loyalty', 'redemption', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On POS checkout, tap "Redeem Points" for customer with 100 points', expected_result: 'Maximum redeemable amount shown. Enter points to redeem: 50' },
      { description: 'Apply redemption to ₹500 invoice', expected_result: 'Invoice total reduced to ₹450. Customer points balance: 50.' },
    ],
  },
  {
    title: 'Customer statement report shows correct closing balance',
    module: 'Customers',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Customer with transactions in date range.',
    tags: ['customers', 'reports', 'statement', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Generate customer statement for last month', expected_result: 'Shows: Opening balance + Sales - Payments = Closing balance. Math checks out.' },
    ],
  },
  {
    title: 'Customer search works by name and phone',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Multiple customers exist.',
    tags: ['customers', 'search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search by partial name "meena"', expected_result: 'Matching customers shown' },
      { description: 'Search by phone number "9988"', expected_result: 'Customer with that phone shown' },
    ],
  },
  {
    title: 'Delete customer with outstanding balance is blocked',
    module: 'Customers',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Customer with outstanding > 0.',
    tags: ['customers', 'delete', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to delete customer with outstanding balance', expected_result: 'Error: "Cannot delete customer with outstanding balance"' },
    ],
  },
  {
    title: 'Top customers report shows highest revenue customers',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple customers with different purchase totals.',
    tags: ['customers', 'analytics', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Customers > Top Customers (last 30 days)', expected_result: 'List sorted by revenue descending. Top customer at #1 with correct total.' },
    ],
  },
  {
    title: 'Customer group discounts apply automatically on sale',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Customer group "Wholesale" with 10% discount configured.',
    tags: ['customers', 'discount', 'groups'],
    is_regression: false,
    steps: [
      { description: 'Add POS sale for customer in Wholesale group', expected_result: 'Cart auto-applies 10% group discount to all eligible items' },
    ],
  },
  {
    title: 'Import customers from CSV',
    module: 'Customers',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Valid CSV with Name, Phone, Email columns.',
    tags: ['customers', 'import', 'csv'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Customers > Import > select CSV', expected_result: 'Preview shows parsed data' },
      { description: 'Import', expected_result: 'Customers created. Summary: X imported, Y skipped (duplicates).' },
    ],
  },
  {
    title: 'Customer birthday notification is sent on birthday date',
    module: 'Customers',
    priority: 'low',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Customer birthday set to today. Birthday notifications enabled.',
    tags: ['customers', 'notifications', 'birthday'],
    is_regression: false,
    steps: [
      { description: 'Open app on customer birthday date', expected_result: 'Notification: "🎂 Today is Meena Devi\'s birthday!" shown in notification center' },
    ],
  },

  // ─── EXPENSES (12) ─────────────────────────────────────────────────────
  {
    title: 'Record business expense with category and receipt',
    module: 'Expenses',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Expense categories configured.',
    tags: ['smoke', 'regression', 'expenses', 'add'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Expenses > Add Expense', expected_result: 'Expense form opens' },
      { description: 'Enter: Amount ₹1,500, Category: Rent, Date: today, Description: "July office rent", attach photo of receipt', expected_result: 'Form filled' },
      { description: 'Save expense', expected_result: 'Expense recorded. Visible in expense list with all details.' },
    ],
  },
  {
    title: 'Expense with zero amount is rejected',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'Add Expense form open.',
    tags: ['expenses', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Enter Amount: 0 and try to save', expected_result: 'Error: "Expense amount must be greater than zero"' },
    ],
  },
  {
    title: 'Expense report shows category-wise breakdown',
    module: 'Expenses',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple expenses in different categories.',
    tags: ['expenses', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Expenses > Report for this month', expected_result: 'Pie chart or table shows expense breakdown: Rent 40%, Utilities 20%, Transport 15%, etc.' },
    ],
  },
  {
    title: 'Expense category can be added and used immediately',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'User with settings access.',
    tags: ['expenses', 'settings', 'category'],
    is_regression: false,
    steps: [
      { description: 'Add new expense category "Marketing"', expected_result: 'Category created' },
      { description: 'Create new expense and select "Marketing" category', expected_result: 'New category available immediately in dropdown' },
    ],
  },
  {
    title: 'Edit expense updates all fields correctly',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Expense exists.',
    tags: ['expenses', 'edit'],
    is_regression: false,
    steps: [
      { description: 'Edit existing expense, change amount from ₹1,500 to ₹1,800', expected_result: 'Amount updated. Expense report recalculates.' },
    ],
  },
  {
    title: 'Delete expense removes it from monthly total',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Expense of ₹500 exists.',
    tags: ['expenses', 'delete'],
    is_regression: false,
    steps: [
      { description: 'Delete expense of ₹500', expected_result: 'Expense removed. Monthly total decreases by ₹500.' },
    ],
  },
  {
    title: 'Future-dated expense is flagged with warning',
    module: 'Expenses',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Add Expense form.',
    tags: ['expenses', 'validation', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Set expense date to 3 months in future', expected_result: 'Warning: "Expense date is in the future. Are you sure?" Allowed with confirmation.' },
    ],
  },
  {
    title: 'Expense receipt image is viewable after save',
    module: 'Expenses',
    priority: 'low',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Expense with attached receipt photo.',
    tags: ['expenses', 'receipt', 'image'],
    is_regression: false,
    steps: [
      { description: 'Open expense and tap receipt thumbnail', expected_result: 'Full-screen image view opens. Image is legible.' },
    ],
  },
  {
    title: 'Expense export to PDF for accountant sharing',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Expenses for current month exist.',
    tags: ['expenses', 'export', 'pdf'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Expenses > Export PDF for this month', expected_result: 'PDF with all expenses, categories, and total generated. Shareable.' },
    ],
  },
  {
    title: 'Recurring expense auto-creates on configured schedule',
    module: 'Expenses',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Recurring expense set: Rent ₹10,000, monthly on 1st.',
    tags: ['expenses', 'recurring', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On 1st of next month, open the app', expected_result: 'Recurring expense ₹10,000 Rent automatically created for this month' },
    ],
  },
  {
    title: 'Expense search by description finds correct entry',
    module: 'Expenses',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Multiple expenses with different descriptions.',
    tags: ['expenses', 'search'],
    is_regression: false,
    steps: [
      { description: 'Search "electricity" in expenses', expected_result: 'Only electricity-related expenses shown' },
    ],
  },
  {
    title: 'P&L report includes expenses in correct period',
    module: 'Expenses',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Expenses and sales exist for the month.',
    tags: ['expenses', 'reports', 'pnl', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Profit & Loss for this month', expected_result: 'Report shows Revenue, Cost of Goods, Gross Profit, Expenses (itemized), Net Profit' },
      { description: 'Verify: Net Profit = Gross Profit - Total Expenses', expected_result: 'Calculation is accurate' },
    ],
  },

  // ─── REPORTS (15) ──────────────────────────────────────────────────────
  {
    title: 'Sales report for custom date range shows correct totals',
    module: 'Reports',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Sales exist across multiple dates.',
    tags: ['smoke', 'regression', 'reports', 'sales'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Sales Report, set range: first 10 days of month', expected_result: 'Report loads with all sales in range' },
      { description: 'Verify total matches sum of invoices in range', expected_result: 'Total is accurate' },
    ],
  },
  {
    title: 'Profit & Loss report calculates net profit correctly',
    module: 'Reports',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Sales, purchases, and expenses recorded for the month.',
    tags: ['regression', 'reports', 'pnl'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > P&L', expected_result: 'P&L loads' },
      { description: 'Verify: Net Profit = Sales Revenue - COGS - Expenses', expected_result: 'Values match when cross-checked' },
    ],
  },
  {
    title: 'GSTR-1 report shows correct outward supply summary',
    module: 'Reports',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Sales with different GST rates made.',
    tags: ['reports', 'gst', 'gstr1', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > GSTR-1 for this month', expected_result: 'Report shows B2B sales, B2C sales, HSN summary with correct GST amounts' },
    ],
  },
  {
    title: 'Inventory report shows stock levels per product',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Products with stock exist.',
    tags: ['reports', 'inventory', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Inventory', expected_result: 'All products listed with current stock, value, and reorder status' },
    ],
  },
  {
    title: 'Top selling products report is sorted by quantity',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple products sold in different quantities.',
    tags: ['reports', 'analytics', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Top Products (last 30 days)', expected_result: 'Products ranked by units sold. #1 product has highest quantity.' },
    ],
  },
  {
    title: 'Report export to PDF is correctly formatted',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Report data exists.',
    tags: ['reports', 'export', 'pdf', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Generate any report and tap Export PDF', expected_result: 'PDF with business name, report period, data table, and total generated correctly' },
    ],
  },
  {
    title: 'Cash flow report tracks daily cash in and out',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Cash sales and cash expenses recorded.',
    tags: ['reports', 'cashflow', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Cash Flow for this week', expected_result: 'Daily bar chart shows Cash In (sales), Cash Out (expenses/payments), Net per day' },
    ],
  },
  {
    title: 'Outstanding receivables report shows all unpaid invoices',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple customers with outstanding balances.',
    tags: ['reports', 'receivables', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Outstanding Receivables', expected_result: 'List of all customers with outstanding amounts, invoice dates, and aging (0-30, 31-60, 60+ days)' },
    ],
  },
  {
    title: 'Report with no data in date range shows empty state',
    module: 'Reports',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'No transactions in selected date range.',
    tags: ['reports', 'edge-case', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Generate sales report for date range with no data', expected_result: 'Empty state shown: "No transactions found for selected period." No crash.' },
    ],
  },
  {
    title: 'Supplier outstanding report shows all payables',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multiple suppliers with balances.',
    tags: ['reports', 'payables', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Supplier Outstanding', expected_result: 'All suppliers with outstanding balances listed. Total payable correct.' },
    ],
  },
  {
    title: 'Slow report generation on large dataset shows progress indicator',
    module: 'Reports',
    priority: 'medium',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Database with 1+ years of transactions.',
    tags: ['reports', 'performance', 'ux'],
    is_regression: false,
    steps: [
      { description: 'Generate annual sales report', expected_result: 'Progress indicator shown during generation. Report completes within 30 seconds.' },
    ],
  },
  {
    title: 'Day close report reconciles opening and closing cash',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'POS session with cash transactions.',
    tags: ['reports', 'dayclose', 'pos', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Run Day Close Report at end of business day', expected_result: 'Report shows: Opening Cash, Total Cash Sales, Total Cash Expenses, Expected Closing Cash' },
    ],
  },
  {
    title: 'Report scheduled email delivery sends on configured time',
    module: 'Reports',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Email report scheduled: Daily Sales Summary at 9 PM.',
    tags: ['reports', 'email', 'scheduled'],
    is_regression: false,
    steps: [
      { description: 'Wait for scheduled report delivery time (9 PM)', expected_result: 'Email received at configured address with daily sales summary PDF' },
    ],
  },
  {
    title: 'HSN summary report shows taxable value per HSN code',
    module: 'Reports',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Products with different HSN codes sold.',
    tags: ['reports', 'gst', 'hsn', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > HSN Summary', expected_result: 'Each HSN code shows: Taxable Value, CGST, SGST, IGST totals' },
    ],
  },
  {
    title: 'Report data matches exported CSV row count',
    module: 'Reports',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Report with known number of rows.',
    tags: ['reports', 'export', 'csv', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Run report showing 47 invoices on screen', expected_result: 'Tap Export CSV. Downloaded file has exactly 47 data rows (plus header).' },
    ],
  },

  // ─── SUBSCRIPTION (10) ─────────────────────────────────────────────────
  {
    title: 'Active subscription unlocks premium features',
    module: 'Subscription',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Account on free plan.',
    tags: ['subscription', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Upgrade to Pro plan', expected_result: 'Payment processed successfully' },
      { description: 'Access a premium feature (e.g., Advanced Reports)', expected_result: 'Feature accessible without upgrade prompt' },
    ],
  },
  {
    title: 'Free plan restricts access to premium features',
    module: 'Subscription',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Account on free plan.',
    tags: ['subscription', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to access Advanced Reports on free plan', expected_result: 'Upgrade prompt shown: "This feature requires Pro plan. Upgrade now."' },
    ],
  },
  {
    title: 'Trial period countdown shows days remaining',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Account in trial period.',
    tags: ['subscription', 'trial', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Subscription / Profile', expected_result: 'Trial banner shows: "X days remaining in your trial. Upgrade to continue."' },
    ],
  },
  {
    title: 'Expired subscription restricts app to read-only mode',
    module: 'Subscription',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Subscription expiry date passed.',
    tags: ['subscription', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open app with expired subscription', expected_result: 'Subscription expired banner shown. New sales, purchases, and edits blocked. View-only access to historical data.' },
    ],
  },
  {
    title: 'Plan upgrade confirmation email sent after payment',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Account on free plan.',
    tags: ['subscription', 'payment', 'email'],
    is_regression: false,
    steps: [
      { description: 'Complete plan upgrade payment', expected_result: 'Confirmation email received: subscription details, renewal date, invoice' },
    ],
  },
  {
    title: 'Subscription renewal date is correct after purchase',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Annual plan purchased on 1 July 2025.',
    tags: ['subscription', 'billing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Subscription > Plan Details', expected_result: 'Renewal date shown as 1 July 2026' },
    ],
  },
  {
    title: 'Multi-user seats cannot exceed plan limit',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Basic plan with 3 user seats. 3 users already added.',
    tags: ['subscription', 'users', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to add a 4th user', expected_result: 'Error: "User limit reached for your plan (3/3). Upgrade for more users."' },
    ],
  },
  {
    title: 'Grace period allows data access 7 days after expiry',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Subscription expired 3 days ago (within grace period).',
    tags: ['subscription', 'grace-period', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open app 3 days after subscription expiry', expected_result: 'App accessible with banner: "Subscription expired 3 days ago. Renew within 4 days to avoid data lock." New transactions blocked.' },
    ],
  },
  {
    title: 'Downgrade plan removes access to premium features',
    module: 'Subscription',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Account on Pro plan.',
    tags: ['subscription', 'downgrade', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Downgrade from Pro to Basic plan', expected_result: 'Downgrade effective at next billing cycle. Warning: "You will lose access to [X premium features] on [renewal date]"' },
    ],
  },
  {
    title: 'Invalid promo code shows clear error',
    module: 'Subscription',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Subscription purchase screen.',
    tags: ['subscription', 'promo', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Enter promo code: FAKECODE99', expected_result: 'Error: "Invalid or expired promo code"' },
    ],
  },

  // ─── SETTINGS (10) ─────────────────────────────────────────────────────
  {
    title: 'Business name change reflects across all invoices',
    module: 'Settings',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Business name currently "CraftX Store".',
    tags: ['settings', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Business Profile > change name to "CraftX Retail"', expected_result: 'Name updated' },
      { description: 'Generate a new invoice', expected_result: 'Invoice header shows "CraftX Retail"' },
    ],
  },
  {
    title: 'GST number configuration validates GSTIN format',
    module: 'Settings',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Settings > Business Profile open.',
    tags: ['settings', 'gst', 'validation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Enter GSTIN: ABC123 (invalid format)', expected_result: 'Error: "Invalid GSTIN format"' },
      { description: 'Enter valid GSTIN: 29ABCDE1234F1Z5', expected_result: 'GSTIN saved. Appears on all new invoices.' },
    ],
  },
  {
    title: 'Invoice prefix and starting number configurable',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Settings > Invoice Settings open.',
    tags: ['settings', 'invoice', 'numbering'],
    is_regression: false,
    steps: [
      { description: 'Set prefix: "INV-2025-" and starting number: 1001', expected_result: 'Settings saved' },
      { description: 'Create new invoice', expected_result: 'Invoice number is INV-2025-1001' },
    ],
  },
  {
    title: 'Payment modes can be enabled or disabled',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'UPI payment mode currently enabled.',
    tags: ['settings', 'payment', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Payment Modes and disable UPI', expected_result: 'UPI toggled off' },
      { description: 'Open POS checkout', expected_result: 'UPI option no longer shown in payment methods' },
    ],
  },
  {
    title: 'Tax settings: multiple GST rates configurable',
    module: 'Settings',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Settings > Tax Configuration open.',
    tags: ['settings', 'gst', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Verify GST rates 0%, 5%, 12%, 18%, 28% are configured', expected_result: 'All standard GST rates available' },
      { description: 'Add custom rate: 3% for gold', expected_result: 'Custom rate saved and available in product GST dropdown' },
    ],
  },
  {
    title: 'Low stock threshold configured globally applies to all products',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Global low stock threshold: 10.',
    tags: ['settings', 'inventory', 'alerts'],
    is_regression: false,
    steps: [
      { description: 'Set global low stock threshold to 5 in Settings', expected_result: 'Setting saved' },
      { description: 'Product with stock 7 should now be above threshold', expected_result: 'Product no longer appears in low stock alerts (was showing before threshold change)' },
    ],
  },
  {
    title: 'Printer settings save correctly and persist',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Bluetooth printer paired.',
    tags: ['settings', 'printing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Printer, select paired printer, set paper size: 80mm', expected_result: 'Settings saved' },
      { description: 'Restart app and check printer settings', expected_result: 'Printer selection and paper size still configured correctly' },
    ],
  },
  {
    title: 'Date format change reflects in all displays',
    module: 'Settings',
    priority: 'low',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Date format currently DD/MM/YYYY.',
    tags: ['settings', 'localization'],
    is_regression: false,
    steps: [
      { description: 'Change date format to MM-DD-YYYY', expected_result: 'Setting saved' },
      { description: 'View any invoice or report', expected_result: 'Dates displayed in MM-DD-YYYY format throughout app' },
    ],
  },
  {
    title: 'Business logo upload appears on invoices',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Settings > Business Profile. Logo image available.',
    tags: ['settings', 'invoice', 'branding'],
    is_regression: false,
    steps: [
      { description: 'Upload business logo in Settings', expected_result: 'Logo preview shown in settings' },
      { description: 'Generate invoice', expected_result: 'Business logo appears in invoice header' },
    ],
  },
  {
    title: 'Multi-currency settings can be configured',
    module: 'Settings',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Settings > Currency open.',
    tags: ['settings', 'currency', 'localization'],
    is_regression: false,
    steps: [
      { description: 'Change currency from INR to USD', expected_result: 'Currency symbol changes to $' },
      { description: 'Navigate to POS', expected_result: 'All prices shown with $ symbol' },
    ],
  },

  // ─── PROFILE (8) ───────────────────────────────────────────────────────
  {
    title: 'User can update profile display name',
    module: 'Profile',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'User logged in.',
    tags: ['profile', 'edit'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > Edit and change display name to "Store Manager"', expected_result: 'Display name updated across app' },
    ],
  },
  {
    title: 'Profile shows current subscription plan and expiry',
    module: 'Profile',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Active subscription exists.',
    tags: ['profile', 'subscription', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Profile', expected_result: 'Current plan name, expiry date, and renewal amount displayed' },
    ],
  },
  {
    title: 'Activity log shows last 50 user actions',
    module: 'Profile',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'User with audit log enabled.',
    tags: ['profile', 'audit', 'security'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > Activity Log', expected_result: 'Chronological list of actions: login times, invoice created, product edited, etc.' },
    ],
  },
  {
    title: 'Notification preferences can be toggled per type',
    module: 'Profile',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Profile > Notifications open.',
    tags: ['profile', 'notifications', 'settings'],
    is_regression: false,
    steps: [
      { description: 'Toggle OFF "Low Stock Alerts"', expected_result: 'Setting saved. No low stock notifications sent to this user.' },
      { description: 'Toggle ON "Payment Reminders"', expected_result: 'Payment reminder notifications enabled for this user' },
    ],
  },
  {
    title: 'Profile photo can be uploaded and displayed',
    module: 'Profile',
    priority: 'low',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Camera/gallery permission granted.',
    tags: ['profile', 'avatar', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Tap profile avatar > upload from gallery', expected_result: 'Image picker opens' },
      { description: 'Select image and save', expected_result: 'Profile photo updated and shown in top nav/drawer' },
    ],
  },
  {
    title: 'Linked devices list shows all active sessions',
    module: 'Profile',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Same account logged in on 2 devices.',
    tags: ['profile', 'security', 'sessions'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > Security > Active Sessions', expected_result: 'List shows 2 devices with device type, location, and last active time' },
    ],
  },
  {
    title: 'Remote logout terminates session on other device',
    module: 'Profile',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Account active on 2 devices.',
    tags: ['profile', 'security', 'sessions', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On Device A: Profile > Active Sessions > Sign out Device B', expected_result: 'Device B receives logout notification and is redirected to login screen' },
    ],
  },
  {
    title: 'App version and build number visible in Profile',
    module: 'Profile',
    priority: 'low',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'Profile screen.',
    tags: ['profile', 'about'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > About', expected_result: 'App version (e.g., 2.0.0-rc1) and build number displayed' },
    ],
  },
];
