// Part 3: Cloud Sync, Notifications, Search, Backup, Security, Performance, Offline,
//          Database, API, Printing, GST, Invoice, Analytics test cases

import type { TestCaseDef } from './seed-rm-data-part1';

export const TEST_CASES_PART3: TestCaseDef[] = [
  // ─── CLOUD SYNC (15) ───────────────────────────────────────────────────
  {
    title: 'Data syncs to cloud within 30 seconds of change',
    module: 'Cloud Sync',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Device online. Cloud sync enabled.',
    tags: ['smoke', 'regression', 'cloud-sync'],
    is_regression: true,
    steps: [
      { description: 'Add a new product on Device A', expected_result: 'Product saved locally' },
      { description: 'Wait up to 30 seconds and check Device B (same account)', expected_result: 'New product appears on Device B without manual refresh' },
    ],
  },
  {
    title: 'Offline changes sync completely when connectivity restored',
    module: 'Cloud Sync',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Device offline.',
    tags: ['regression', 'cloud-sync', 'offline'],
    is_regression: true,
    steps: [
      { description: 'Create 3 sales, 1 product edit, and 1 stock adjustment while offline', expected_result: 'All 5 changes saved locally in sync queue' },
      { description: 'Re-enable internet', expected_result: 'All 5 changes sync to server. Sync complete indicator shown. No data loss.' },
    ],
  },
  {
    title: 'Sync conflict resolved in favor of more recent timestamp',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Two devices offline. Same record edited on both.',
    tags: ['cloud-sync', 'conflict', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Device A edits product price to ₹200 at 10:00 AM (offline)', expected_result: 'Local change saved' },
      { description: 'Device B edits same product price to ₹250 at 10:05 AM (offline)', expected_result: 'Local change saved' },
      { description: 'Both devices come online', expected_result: 'Conflict detected. Later timestamp wins: price = ₹250. Conflict log entry created.' },
    ],
  },
  {
    title: 'Sync status indicator shows pending, syncing, synced states',
    module: 'Cloud Sync',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Cloud sync enabled.',
    tags: ['cloud-sync', 'ui', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create sale offline', expected_result: 'Sync indicator shows "Pending sync" badge count' },
      { description: 'Restore internet', expected_result: 'Indicator shows "Syncing..." animation' },
      { description: 'After sync completes', expected_result: 'Indicator shows "Synced ✓" with last sync timestamp' },
    ],
  },
  {
    title: 'Sync queue shows list of pending changes',
    module: 'Cloud Sync',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Offline changes exist in queue.',
    tags: ['cloud-sync', 'queue'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Settings > Cloud Sync > Pending Changes', expected_result: 'List shows each pending change: type (Sale/Product/etc.), entity name, timestamp' },
    ],
  },
  {
    title: 'Force sync manually triggers immediate upload',
    module: 'Cloud Sync',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'User online with pending or recent changes.',
    tags: ['cloud-sync', 'manual'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Settings > Cloud Sync > tap "Sync Now"', expected_result: 'Sync starts immediately. Progress shown. Completes successfully.' },
    ],
  },
  {
    title: 'Sync does not run on metered connection when WiFi-only setting enabled',
    module: 'Cloud Sync',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'WiFi-only sync enabled in settings. Device on mobile data.',
    tags: ['cloud-sync', 'settings', 'network'],
    is_regression: false,
    steps: [
      { description: 'Switch to mobile data with WiFi-only sync enabled', expected_result: 'Sync pauses. Banner: "Sync paused – waiting for WiFi connection"' },
    ],
  },
  {
    title: 'Large data set sync (5000 transactions) completes successfully',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 15,
    is_automation_ready: false,
    preconditions: 'Fresh device login with 5000 transactions on server.',
    tags: ['cloud-sync', 'performance', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Log in to fresh device installation', expected_result: 'Initial sync begins downloading 5000 transactions' },
      { description: 'Monitor sync progress', expected_result: 'Sync completes within 5 minutes. Progress bar accurate. No crash.' },
    ],
  },
  {
    title: 'Sync error due to server downtime shows retry option',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Server unavailable (simulate via airplane mode).',
    tags: ['cloud-sync', 'negative', 'error-handling'],
    is_regression: false,
    steps: [
      { description: 'Trigger sync while server unreachable', expected_result: 'Error: "Sync failed – server unreachable. Changes saved locally." Retry button shown.' },
    ],
  },
  {
    title: 'Deletion syncs correctly – deleted records removed on other devices',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Two devices with same data.',
    tags: ['cloud-sync', 'delete', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Delete product on Device A', expected_result: 'Product deleted locally' },
      { description: 'Wait for sync on Device B', expected_result: 'Product removed from Device B\'s product list' },
    ],
  },
  {
    title: 'Authentication token refreshes automatically during long sync',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Access token about to expire during large sync.',
    tags: ['cloud-sync', 'auth', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Start large sync that takes longer than token lifetime', expected_result: 'Token refreshes in background. Sync continues without interruption or re-login prompt.' },
    ],
  },
  {
    title: 'Sync history log is viewable with timestamps',
    module: 'Cloud Sync',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: false,
    preconditions: 'Multiple sync events occurred.',
    tags: ['cloud-sync', 'audit'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Settings > Cloud Sync > Sync History', expected_result: 'List of sync events: timestamp, records synced, status (success/fail)' },
    ],
  },
  {
    title: 'Multi-user concurrent edits merge correctly without data loss',
    module: 'Cloud Sync',
    priority: 'critical',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Two users editing different fields of same customer simultaneously.',
    tags: ['cloud-sync', 'concurrency', 'regression'],
    is_regression: true,
    steps: [
      { description: 'User A updates customer phone. User B updates customer email. Both save simultaneously.', expected_result: 'After sync: customer has both new phone AND new email. Neither change lost.' },
    ],
  },
  {
    title: 'Device storage full does not corrupt sync queue',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Device storage at 99% capacity.',
    tags: ['cloud-sync', 'edge-case', 'storage'],
    is_regression: false,
    steps: [
      { description: 'Attempt to create and sync records with storage nearly full', expected_result: 'Graceful error: "Storage low – sync paused. Free up space to continue." Existing queue not corrupted.' },
    ],
  },
  {
    title: 'Initial sync progress shown on first login to new device',
    module: 'Cloud Sync',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Account with 6 months of data. Fresh device install.',
    tags: ['cloud-sync', 'onboarding', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Log in on new device', expected_result: 'Initial sync screen shown: "Setting up your data... X of Y records"' },
      { description: 'Wait for completion', expected_result: 'All data available. Dashboard shows correct figures.' },
    ],
  },

  // ─── NOTIFICATIONS (10) ────────────────────────────────────────────────
  {
    title: 'Low stock push notification delivered to device',
    module: 'Notifications',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Push notifications enabled. Product stock about to hit reorder level.',
    tags: ['notifications', 'push', 'inventory', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Complete sale that brings product stock to reorder level', expected_result: 'Push notification delivered: "Low Stock: [Product Name] – Only X units remaining"' },
    ],
  },
  {
    title: 'Payment due reminder notification sent on due date',
    module: 'Notifications',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Customer outstanding payment due today.',
    tags: ['notifications', 'payment', 'reminder', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open app on payment due date', expected_result: 'In-app notification: "Payment due today from [Customer Name] – ₹X outstanding"' },
    ],
  },
  {
    title: 'Notification tap navigates to relevant screen',
    module: 'Notifications',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Notification in notification center.',
    tags: ['notifications', 'navigation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap low stock notification from notification shade', expected_result: 'App opens directly to product\'s inventory screen' },
      { description: 'Tap payment due notification', expected_result: 'App opens to customer ledger / outstanding report' },
    ],
  },
  {
    title: 'Notification preferences control which alerts are received',
    module: 'Notifications',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Low stock notifications disabled in Profile > Notifications.',
    tags: ['notifications', 'settings', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Trigger a low stock event', expected_result: 'No push notification sent. No in-app notification for low stock.' },
    ],
  },
  {
    title: 'Notification badge count shows unread count',
    module: 'Notifications',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: '3 unread notifications exist.',
    tags: ['notifications', 'ui', 'badge'],
    is_regression: false,
    steps: [
      { description: 'View app icon or notification bell', expected_result: 'Badge shows "3"' },
      { description: 'Open notification center and read all', expected_result: 'Badge count clears to 0' },
    ],
  },
  {
    title: 'Subscription renewal reminder sent 7 days before expiry',
    module: 'Notifications',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Subscription expires in 7 days.',
    tags: ['notifications', 'subscription', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On day 7 before expiry, open app', expected_result: 'In-app banner and push notification: "Your subscription expires in 7 days. Renew now to avoid service interruption."' },
    ],
  },
  {
    title: 'Mark all notifications as read clears unread state',
    module: 'Notifications',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Multiple unread notifications.',
    tags: ['notifications', 'ui'],
    is_regression: false,
    steps: [
      { description: 'In notification center, tap "Mark all as read"', expected_result: 'All notifications marked read. Badge count = 0.' },
    ],
  },
  {
    title: 'Delete notification removes it from list',
    module: 'Notifications',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Notifications in list.',
    tags: ['notifications', 'delete'],
    is_regression: false,
    steps: [
      { description: 'Swipe to delete a notification', expected_result: 'Notification removed from list. Unread count decrements if it was unread.' },
    ],
  },
  {
    title: 'Notification for new sale on secondary device (multi-user)',
    module: 'Notifications',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Owner and staff accounts on different devices. Owner notification for sales enabled.',
    tags: ['notifications', 'multi-user', 'sales'],
    is_regression: false,
    steps: [
      { description: 'Staff completes a ₹5,000 sale on their device', expected_result: 'Owner device receives notification: "New sale – ₹5,000 by [Staff Name]"' },
    ],
  },
  {
    title: 'Notifications load correctly with 500+ historical items',
    module: 'Notifications',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Notification history has 500+ items.',
    tags: ['notifications', 'performance', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Open notification center with 500+ items', expected_result: 'List renders quickly with pagination. No crash or excessive memory use.' },
    ],
  },

  // ─── SEARCH (10) ───────────────────────────────────────────────────────
  {
    title: 'Global search finds product by name',
    module: 'Search',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Products, customers, and invoices exist.',
    tags: ['smoke', 'regression', 'search'],
    is_regression: true,
    steps: [
      { description: 'Tap global search icon and type "basmati"', expected_result: 'Search results show "Products" section with matching product(s)' },
    ],
  },
  {
    title: 'Global search finds customer by phone number',
    module: 'Search',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Customer with phone 9876543210 exists.',
    tags: ['search', 'customers', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search "9876543210"', expected_result: 'Customer result shown with name and phone' },
    ],
  },
  {
    title: 'Global search finds invoice by number',
    module: 'Search',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Invoice INV-2025-0050 exists.',
    tags: ['search', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search "INV-2025-0050"', expected_result: 'Invoice appears in "Invoices" section of results' },
    ],
  },
  {
    title: 'Search with no results shows empty state',
    module: 'Search',
    priority: 'medium',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'App with data.',
    tags: ['search', 'edge-case', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Search for a string that matches nothing: "zzznomatch999"', expected_result: 'Empty state: "No results found for \'zzznomatch999\'"' },
    ],
  },
  {
    title: 'Search returns results within 1 second',
    module: 'Search',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Large database (10,000+ records).',
    tags: ['search', 'performance', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Type search query on large database', expected_result: 'Results appear within 1 second of typing' },
    ],
  },
  {
    title: 'Search is case-insensitive',
    module: 'Search',
    priority: 'medium',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'Product "Basmati Rice" exists.',
    tags: ['search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search "BASMATI rice"', expected_result: 'Product "Basmati Rice" found (case-insensitive match)' },
    ],
  },
  {
    title: 'Search result tap navigates to correct detail screen',
    module: 'Search',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Search results visible.',
    tags: ['search', 'navigation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap a product in search results', expected_result: 'Product detail screen opens' },
      { description: 'Back and tap a customer result', expected_result: 'Customer profile opens' },
    ],
  },
  {
    title: 'Recent searches shown when search bar focused',
    module: 'Search',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Previous searches exist.',
    tags: ['search', 'ux'],
    is_regression: false,
    steps: [
      { description: 'Tap search bar without typing', expected_result: 'Recent search terms shown below search bar' },
    ],
  },
  {
    title: 'Search with special characters does not crash',
    module: 'Search',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Search bar open.',
    tags: ['search', 'security', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Search for: <script>alert(1)</script>', expected_result: 'App treats as plain text. No script executes. No crash. Empty results shown.' },
    ],
  },
  {
    title: 'Search finds supplier by partial name',
    module: 'Search',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Supplier "Sharma Wholesale" exists.',
    tags: ['search', 'suppliers'],
    is_regression: false,
    steps: [
      { description: 'Search "Sharma"', expected_result: '"Sharma Wholesale" appears in Suppliers section of results' },
    ],
  },

  // ─── BACKUP & RESTORE (12) ─────────────────────────────────────────────
  {
    title: 'Manual backup creates and downloads backup file',
    module: 'Backup & Restore',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Storage permission granted. Data exists.',
    tags: ['smoke', 'regression', 'backup'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Backup > Create Backup', expected_result: 'Backup creation starts' },
      { description: 'Wait for completion', expected_result: 'Backup file created (e.g., RM_backup_20250728.zip). Share/save dialog appears.' },
    ],
  },
  {
    title: 'Restore from backup restores all data correctly',
    module: 'Backup & Restore',
    priority: 'critical',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Valid backup file from a known state. Test device available.',
    tags: ['regression', 'backup', 'restore'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Restore > select backup file', expected_result: 'Backup summary shown: date, record counts' },
      { description: 'Confirm restore', expected_result: 'App restores data. After restart: products, customers, invoices match backup state.' },
    ],
  },
  {
    title: 'Automated scheduled backup runs at configured time',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Auto backup set to daily at 11 PM.',
    tags: ['backup', 'scheduled', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Wait for scheduled backup time (11 PM)', expected_result: 'Backup created automatically. Last backup time updated in settings.' },
    ],
  },
  {
    title: 'Restore from corrupted backup shows error',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Intentionally corrupted .zip file available.',
    tags: ['backup', 'negative', 'restore'],
    is_regression: false,
    steps: [
      { description: 'Attempt restore with corrupted backup file', expected_result: 'Error: "Backup file is corrupted or incompatible. Restore aborted. Existing data unchanged."' },
    ],
  },
  {
    title: 'Backup from older app version restores on newer version',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Backup file from v1.5 of app. Current app is v2.0.',
    tags: ['backup', 'migration', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt to restore v1.5 backup on v2.0 app', expected_result: 'Migration runs automatically. Data accessible in v2.0 format. No manual intervention needed.' },
    ],
  },
  {
    title: 'Backup file includes all modules (products, sales, customers)',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Data exists in products, sales, customers.',
    tags: ['backup', 'completeness', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create backup and restore on clean install', expected_result: 'All modules populated: Products, Customers, Invoices, Expenses, Suppliers match original counts' },
    ],
  },
  {
    title: 'Cloud backup upload to Google Drive succeeds',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Google Drive integration authorized.',
    tags: ['backup', 'cloud', 'google-drive'],
    is_regression: false,
    steps: [
      { description: 'Tap "Backup to Google Drive"', expected_result: 'Backup file uploaded to designated Drive folder. Success: "Backup saved to Google Drive".' },
    ],
  },
  {
    title: 'Restore blocks if backup is from different business account',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Backup file from different business GSTIN/account.',
    tags: ['backup', 'security', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Attempt to restore backup from different business account', expected_result: 'Warning: "Backup belongs to a different business account. Restore may overwrite your data. Proceed?" with clear confirmation required.' },
    ],
  },
  {
    title: 'Backup size is shown before download',
    module: 'Backup & Restore',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: false,
    preconditions: 'Backup created.',
    tags: ['backup', 'ux'],
    is_regression: false,
    steps: [
      { description: 'Create backup', expected_result: 'Success screen shows backup file size (e.g., "Backup size: 4.2 MB")' },
    ],
  },
  {
    title: 'Partial restore (products only) is supported',
    module: 'Backup & Restore',
    priority: 'medium',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Backup file exists. Only products need restoring.',
    tags: ['backup', 'selective-restore'],
    is_regression: false,
    steps: [
      { description: 'Select restore, choose "Products only" option', expected_result: 'Only products restored. Customers, sales, expenses untouched.' },
    ],
  },
  {
    title: 'Backup during active sync does not corrupt data',
    module: 'Backup & Restore',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Sync actively running.',
    tags: ['backup', 'concurrency', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Trigger backup while cloud sync is in progress', expected_result: 'Backup waits for sync to complete, OR takes a consistent snapshot. No partial/corrupted backup.' },
    ],
  },
  {
    title: 'Last backup timestamp visible in Settings',
    module: 'Backup & Restore',
    priority: 'medium',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'At least one backup performed.',
    tags: ['backup', 'ui', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Backup', expected_result: '"Last backup: [date and time]" shown. Days since last backup shown.' },
    ],
  },

  // ─── SECURITY (15) ─────────────────────────────────────────────────────
  {
    title: 'SQL injection in product name field is sanitized',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['security', 'sql-injection', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Enter product name: \' OR 1=1; DROP TABLE products; --', expected_result: 'Input saved as plain text string. No SQL executed. Database unaffected.' },
    ],
  },
  {
    title: 'XSS payload in customer name field is escaped',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Add Customer form.',
    tags: ['security', 'xss', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Enter customer name: <script>alert("XSS")</script>', expected_result: 'Name saved as plain text. No JavaScript executes. Displayed as escaped text in UI.' },
    ],
  },
  {
    title: 'API calls without authentication token are rejected with 401',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'API endpoint available.',
    tags: ['security', 'api', 'auth', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Call any API endpoint without Authorization header', expected_result: 'HTTP 401 Unauthorized response. No data returned.' },
    ],
  },
  {
    title: 'Staff user cannot access another business\'s data via API',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Two separate business accounts exist.',
    tags: ['security', 'data-isolation', 'api', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Authenticate as Business A', expected_result: 'Get valid token for Business A' },
      { description: 'Use Business A token to request Business B\'s customer data', expected_result: 'HTTP 403 Forbidden. Business B data not accessible.' },
    ],
  },
  {
    title: 'Privilege escalation: staff cannot perform admin actions',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Staff account (non-admin) logged in.',
    tags: ['security', 'rbac', 'privilege-escalation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'As staff, attempt API call to delete a product (admin-only action)', expected_result: 'HTTP 403 Forbidden. Action not performed.' },
    ],
  },
  {
    title: 'JWT token cannot be used after logout',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'User logged in. JWT token captured.',
    tags: ['security', 'jwt', 'auth', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Logout from app', expected_result: 'Session terminated' },
      { description: 'Use previously captured JWT token in API request', expected_result: 'HTTP 401. Token invalidated on logout.' },
    ],
  },
  {
    title: 'Sensitive data is not logged in app logs',
    module: 'Security',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Developer tools / logcat accessible.',
    tags: ['security', 'data-privacy', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Log in and perform financial transactions', expected_result: 'Check device logs. No passwords, JWT tokens, or credit card data logged in plaintext.' },
    ],
  },
  {
    title: 'PIN lock cannot be bypassed by pressing back',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'PIN lock active.',
    tags: ['security', 'pin', 'regression'],
    is_regression: true,
    steps: [
      { description: 'PIN lock screen shown', expected_result: 'Back button press does not dismiss PIN screen or navigate to app' },
    ],
  },
  {
    title: 'Sensitive fields (GSTIN, bank details) are masked in UI',
    module: 'Security',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'GSTIN and bank account details configured.',
    tags: ['security', 'data-masking', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Settings > Business Profile > Bank Details', expected_result: 'Account number partially masked: ****6789. Full number visible only after re-authentication.' },
    ],
  },
  {
    title: 'App data is encrypted on device storage',
    module: 'Security',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Rooted device for verification (test environment only).',
    tags: ['security', 'encryption', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Access device file system and locate app database', expected_result: 'Database file is encrypted. Cannot read contents as plaintext with a hex editor.' },
    ],
  },
  {
    title: 'Rate limiting blocks more than 10 API calls per second',
    module: 'Security',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'API access configured.',
    tags: ['security', 'api', 'rate-limiting'],
    is_regression: false,
    steps: [
      { description: 'Send 15 API requests per second from same client', expected_result: 'After 10 requests, subsequent requests receive HTTP 429 Too Many Requests until rate window resets' },
    ],
  },
  {
    title: 'Session token stored securely in Keystore/Keychain',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'App installed and logged in.',
    tags: ['security', 'auth', 'keystore', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Inspect where auth token is stored post-login', expected_result: 'Token stored in Android Keystore (not SharedPreferences in plaintext). Verified via code review or secure storage audit.' },
    ],
  },
  {
    title: 'Direct object reference: cannot access other user\'s invoice by ID',
    module: 'Security',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Two user accounts with different invoices.',
    tags: ['security', 'idor', 'api', 'regression'],
    is_regression: true,
    steps: [
      { description: 'User A gets their invoice ID. Authenticate as User B and request User A\'s invoice by ID', expected_result: 'HTTP 403 or 404. User B cannot access User A\'s invoice.' },
    ],
  },
  {
    title: 'Audit log records all admin actions with user and timestamp',
    module: 'Security',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Audit log enabled.',
    tags: ['security', 'audit', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Admin deletes a product', expected_result: 'Audit log entry: "Product deleted – [Product Name] – by [Admin User] – [timestamp]"' },
    ],
  },
  {
    title: 'Biometric enrollment not available to staff role',
    module: 'Security',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Staff account.',
    tags: ['security', 'biometric', 'rbac'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > Security as staff user', expected_result: 'Biometric enrollment option not shown. PIN management limited to own PIN.' },
    ],
  },

  // ─── PERFORMANCE (10) ──────────────────────────────────────────────────
  {
    title: 'App cold start loads to Dashboard within 3 seconds',
    module: 'Performance',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'App fully closed. Device has typical hardware (2GB RAM).',
    tags: ['performance', 'startup', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Force close app and restart from cold state', expected_result: 'Dashboard visible and interactive within 3 seconds. Measured via stopwatch.' },
    ],
  },
  {
    title: 'POS screen loads product search within 500ms',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: '10,000 products in database.',
    tags: ['performance', 'pos', 'search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open POS and type 3 characters in product search', expected_result: 'Search results appear within 500ms' },
    ],
  },
  {
    title: 'Invoice generation for 50-item sale completes in under 2 seconds',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: '50 distinct products added to POS cart.',
    tags: ['performance', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap Confirm Payment with 50 items in cart', expected_result: 'Invoice generated within 2 seconds. PDF preview loads within 3 seconds.' },
    ],
  },
  {
    title: 'Monthly sales report for 10,000 invoices generates in under 10 seconds',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Database with 10,000 invoices for the month.',
    tags: ['performance', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Request monthly sales report with 10,000 invoices', expected_result: 'Report loads within 10 seconds. Values correct.' },
    ],
  },
  {
    title: 'App memory usage stays below 200MB under typical use',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'App running on device. Developer tools available.',
    tags: ['performance', 'memory', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Use app for 15 minutes: browse products, create sale, view reports', expected_result: 'Memory usage remains below 200MB. No memory leak detected (usage stable over time).' },
    ],
  },
  {
    title: 'Concurrent 5 users performing sales shows no data conflict',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: '5 devices logged in to same business account.',
    tags: ['performance', 'concurrency', 'regression'],
    is_regression: true,
    steps: [
      { description: 'All 5 devices simultaneously complete a sale', expected_result: '5 distinct invoices created with unique numbers. No race condition. Stock correctly decremented.' },
    ],
  },
  {
    title: 'Scrolling through 10,000 product list is smooth (60fps)',
    module: 'Performance',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: '10,000 products loaded.',
    tags: ['performance', 'products', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Scroll through product list rapidly', expected_result: 'Scroll is smooth. No dropped frames. Items load as you scroll (lazy loading).' },
    ],
  },
  {
    title: 'Battery drain during 1 hour active use is under 15%',
    module: 'Performance',
    priority: 'medium',
    estimated_minutes: 60,
    is_automation_ready: false,
    preconditions: 'Device at 100% battery. Typical retail workflow.',
    tags: ['performance', 'battery'],
    is_regression: false,
    steps: [
      { description: 'Use app actively for 1 hour (sales, reports, inventory checks)', expected_result: 'Battery drain less than 15% in 1 hour of active use' },
    ],
  },
  {
    title: 'Large product import (5000 rows) completes without timeout',
    module: 'Performance',
    priority: 'high',
    estimated_minutes: 15,
    is_automation_ready: false,
    preconditions: 'CSV with 5000 valid product rows.',
    tags: ['performance', 'import', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Import 5000-row CSV', expected_result: 'Import completes within 5 minutes. Progress shown. No timeout or crash.' },
    ],
  },
  {
    title: 'App remains responsive after 8 hours continuous use',
    module: 'Performance',
    priority: 'medium',
    estimated_minutes: 480,
    is_automation_ready: false,
    preconditions: 'App open for extended shift simulation.',
    tags: ['performance', 'stability', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Run app with periodic sales and stock checks over 8 hours', expected_result: 'No crash. Memory stable. Response times consistent with fresh launch.' },
    ],
  },

  // ─── OFFLINE MODE (12) ─────────────────────────────────────────────────
  {
    title: 'App is fully functional for sales while completely offline',
    module: 'Offline Mode',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'App has synced data. Airplane mode ON.',
    tags: ['smoke', 'regression', 'offline'],
    is_regression: true,
    steps: [
      { description: 'Enable airplane mode', expected_result: 'App shows offline banner' },
      { description: 'Create a complete sale with 3 products, collect payment, generate invoice', expected_result: 'Sale completes fully offline. Invoice created. Stock decremented locally.' },
    ],
  },
  {
    title: 'Offline POS uses locally cached product and pricing data',
    module: 'Offline Mode',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Products synced. Device offline.',
    tags: ['offline', 'pos', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open POS while offline', expected_result: 'Product catalog loads from local cache. Search works. Prices correct.' },
    ],
  },
  {
    title: 'Offline sale syncs to server when back online',
    module: 'Offline Mode',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Sale completed offline.',
    tags: ['offline', 'sync', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Restore internet after offline sale', expected_result: 'Sale syncs within 30 seconds. Invoice visible on server and other devices.' },
    ],
  },
  {
    title: 'Offline indicator clearly communicates connection status',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: false,
    preconditions: 'App online.',
    tags: ['offline', 'ui', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Switch to airplane mode while on Dashboard', expected_result: 'Offline banner or icon appears within 5 seconds: "You are offline"' },
      { description: 'Restore internet', expected_result: 'Online indicator returns. Sync triggers automatically.' },
    ],
  },
  {
    title: 'Reports load from cache when offline',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Reports loaded at least once while online.',
    tags: ['offline', 'reports'],
    is_regression: false,
    steps: [
      { description: 'Go offline and navigate to Sales Report', expected_result: 'Cached report data shown with notice: "Showing data as of [last sync time]"' },
    ],
  },
  {
    title: 'Multiple offline sales queue and sync in correct order',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Device offline.',
    tags: ['offline', 'sync', 'ordering', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create 5 sales offline in sequence (Sale A at 10:00, B at 10:01... E at 10:04)', expected_result: 'All 5 queued locally' },
      { description: 'Come online', expected_result: 'All 5 sync in chronological order. Invoice numbers assigned in correct sequence.' },
    ],
  },
  {
    title: 'Offline conflict: same product sold on 2 devices creates shortage alert',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Product stock = 5. Both devices offline.',
    tags: ['offline', 'conflict', 'inventory', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Device A sells 3 units offline. Device B sells 4 units offline.', expected_result: 'Both sales saved locally' },
      { description: 'Both come online', expected_result: 'Conflict detected: total sold (7) > available stock (5). Alert raised. Manager notified.' },
    ],
  },
  {
    title: 'Product edits made offline apply correctly after sync',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Device offline.',
    tags: ['offline', 'products', 'sync', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Edit product price from ₹200 to ₹220 while offline', expected_result: 'Local DB shows ₹220' },
      { description: 'Come online', expected_result: 'Server and all other devices update to ₹220' },
    ],
  },
  {
    title: 'App handles intermittent connectivity gracefully',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Simulate flapping connection.',
    tags: ['offline', 'edge-case', 'network'],
    is_regression: false,
    steps: [
      { description: 'Toggle airplane mode on/off every 10 seconds for 2 minutes', expected_result: 'No crash. App queues work during offline periods and syncs during online windows. No data corruption.' },
    ],
  },
  {
    title: 'Offline mode does not allow actions requiring server validation',
    module: 'Offline Mode',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Device offline.',
    tags: ['offline', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Try to apply promo code while offline', expected_result: 'Error: "Promo code validation requires internet connection"' },
    ],
  },
  {
    title: 'Offline data persists across app restarts',
    module: 'Offline Mode',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Offline sales created.',
    tags: ['offline', 'persistence', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create 3 sales offline, then force close and reopen app (still offline)', expected_result: 'Sync queue shows 3 pending items. Data not lost across restart.' },
    ],
  },
  {
    title: 'Offline GST calculation uses cached tax rates',
    module: 'Offline Mode',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'GST rates synced. Device offline.',
    tags: ['offline', 'gst', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create sale with GST products while offline', expected_result: 'GST calculated correctly using cached rates. Invoice totals match expected GST amounts.' },
    ],
  },

  // ─── DATABASE (8) ──────────────────────────────────────────────────────
  {
    title: 'Database migration runs automatically on app update',
    module: 'Database',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'App v1.9 installed. Update to v2.0 available.',
    tags: ['database', 'migration', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Update app from v1.9 to v2.0', expected_result: 'Migration runs silently. All existing data preserved. New fields initialized with defaults. No user action needed.' },
    ],
  },
  {
    title: 'Database integrity check passes after heavy use',
    module: 'Database',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'After 8 hours of use with transactions.',
    tags: ['database', 'integrity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Run database integrity check (Settings > Advanced > Check DB)', expected_result: 'Result: "Database integrity: OK. No corruption found."' },
    ],
  },
  {
    title: 'Orphaned records are not created on cascading deletes',
    module: 'Database',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Customer with linked invoices.',
    tags: ['database', 'data-integrity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Delete a customer who has historical invoices', expected_result: 'Invoices preserved (soft-link) or blocked from deletion. No orphaned invoice records without customer reference.' },
    ],
  },
  {
    title: 'Database size grows predictably with data volume',
    module: 'Database',
    priority: 'medium',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Baseline DB size known. 1000 transactions to create.',
    tags: ['database', 'performance'],
    is_regression: false,
    steps: [
      { description: 'Add 1000 invoices with average 5 items each', expected_result: 'DB size increase is proportional and within expected bounds (< 50MB for 1000 invoices)' },
    ],
  },
  {
    title: 'Concurrent writes do not cause database lock errors',
    module: 'Database',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Multiple background processes writing to DB.',
    tags: ['database', 'concurrency', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Trigger simultaneous: sync write + user action write + background backup read', expected_result: 'All operations complete without "database is locked" errors' },
    ],
  },
  {
    title: 'Database WAL mode enables concurrent reads and writes',
    module: 'Database',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'SQLite WAL mode enabled.',
    tags: ['database', 'performance', 'concurrency'],
    is_regression: false,
    steps: [
      { description: 'Read product list while a sync write is in progress', expected_result: 'Read completes without waiting for write to finish. No locking error.' },
    ],
  },
  {
    title: 'Database vacuum runs to reclaim space after bulk delete',
    module: 'Database',
    priority: 'low',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Large number of records deleted.',
    tags: ['database', 'maintenance'],
    is_regression: false,
    steps: [
      { description: 'Delete 5000 records and run vacuum', expected_result: 'DB file size decreases. Space reclaimed.' },
    ],
  },
  {
    title: 'Failed transaction is rolled back completely',
    module: 'Database',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Multi-step transaction: save invoice + deduct stock.',
    tags: ['database', 'transactions', 'data-integrity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Simulate failure mid-transaction (after invoice saved, before stock deducted)', expected_result: 'Invoice not created. Stock unchanged. Full rollback. System in consistent state.' },
    ],
  },

  // ─── API (10) ──────────────────────────────────────────────────────────
  {
    title: 'GET /products returns paginated list with correct count',
    module: 'API',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'API key configured. Products exist.',
    tags: ['api', 'products', 'regression'],
    is_regression: true,
    steps: [
      { description: 'GET /api/v1/products?page=1&limit=20 with valid auth', expected_result: 'Response: 200 OK. Body: { data: [...20 products], total: N, page: 1, per_page: 20 }' },
    ],
  },
  {
    title: 'POST /sales creates invoice and returns invoice ID',
    module: 'API',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Valid auth token. Products in stock.',
    tags: ['api', 'sales', 'regression'],
    is_regression: true,
    steps: [
      { description: 'POST /api/v1/sales with valid sale payload', expected_result: 'Response: 201 Created. Body includes invoice_id, invoice_number, total_amount.' },
    ],
  },
  {
    title: 'API returns 422 for invalid sale payload (missing items)',
    module: 'API',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Valid auth token.',
    tags: ['api', 'validation', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'POST /api/v1/sales with empty items array', expected_result: 'Response: 422 Unprocessable Entity. Body: { error: "items cannot be empty" }' },
    ],
  },
  {
    title: 'API error responses follow consistent JSON structure',
    module: 'API',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'API accessible.',
    tags: ['api', 'error-handling', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Trigger various API errors (401, 403, 404, 422, 500)', expected_result: 'All error responses follow: { error: "...", code: "...", details: {...} }. No stack traces in production.' },
    ],
  },
  {
    title: 'API supports pagination with cursor-based navigation',
    module: 'API',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'More than 100 records exist.',
    tags: ['api', 'pagination', 'regression'],
    is_regression: true,
    steps: [
      { description: 'GET /api/v1/customers?cursor=XXX&limit=50 using cursor from previous response', expected_result: 'Next 50 customers returned. No duplicates from previous page.' },
    ],
  },
  {
    title: 'API webhook fires on new sale completion',
    module: 'API',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Webhook URL configured for sale.created event.',
    tags: ['api', 'webhook'],
    is_regression: false,
    steps: [
      { description: 'Complete a sale in the app', expected_result: 'Webhook delivers POST to configured URL within 5 seconds. Payload includes sale details.' },
    ],
  },
  {
    title: 'API rate limit headers returned on every response',
    module: 'API',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'API accessible.',
    tags: ['api', 'rate-limiting', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Make any authenticated API call', expected_result: 'Response headers include: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset' },
    ],
  },
  {
    title: 'API search endpoint supports full-text across products',
    module: 'API',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Products exist with diverse names.',
    tags: ['api', 'search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'GET /api/v1/search?q=basmati&type=product', expected_result: 'Response includes matching products. Results sorted by relevance.' },
    ],
  },
  {
    title: 'API timeout returns 504 gracefully',
    module: 'API',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Simulate slow database query.',
    tags: ['api', 'performance', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Trigger a long-running report API call that exceeds timeout threshold', expected_result: 'HTTP 504 Gateway Timeout returned. Client shows appropriate error message.' },
    ],
  },
  {
    title: 'API versioning: v1 endpoints remain stable',
    module: 'API',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'v1 API consumers exist.',
    tags: ['api', 'versioning', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Call all v1 API endpoints after v2.0 release', expected_result: 'All v1 endpoints return expected responses. No breaking changes introduced in v2.0.' },
    ],
  },

  // ─── PRINTING (10) ─────────────────────────────────────────────────────
  {
    title: 'Bluetooth thermal printer pairing completes successfully',
    module: 'Printing',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Bluetooth thermal printer (80mm) powered on and discoverable.',
    tags: ['printing', 'bluetooth', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Printer > Add Printer', expected_result: 'Bluetooth device scan finds printer' },
      { description: 'Select printer and pair', expected_result: 'Printer paired. "Connected" status shown. Test print option available.' },
    ],
  },
  {
    title: 'Test print from Settings prints correctly',
    module: 'Printing',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Printer paired.',
    tags: ['printing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Settings > Printer > Test Print', expected_result: 'Test page prints with business name, "Test Print", and date/time' },
    ],
  },
  {
    title: 'Invoice prints with all required fields on 80mm paper',
    module: 'Printing',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Completed invoice. 80mm printer paired.',
    tags: ['printing', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Print invoice from Sales screen', expected_result: 'Receipt printed: Business name, GSTIN, Invoice no., Date, Items table, Subtotal, Tax, Total, Payment mode, Thank you message' },
    ],
  },
  {
    title: 'WiFi printer prints invoice via network',
    module: 'Printing',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'WiFi printer on same network. IP configured in Settings.',
    tags: ['printing', 'wifi', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Print invoice using WiFi printer', expected_result: 'Print job sent via network. Receipt printed correctly within 5 seconds.' },
    ],
  },
  {
    title: 'Printer disconnection during print shows retry option',
    module: 'Printing',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Printer paired.',
    tags: ['printing', 'negative', 'error-handling'],
    is_regression: false,
    steps: [
      { description: 'Turn off printer mid-print job', expected_result: 'Error: "Printer connection lost. Retry?" with retry button shown.' },
    ],
  },
  {
    title: 'GST invoice print shows CGST/SGST breakdown',
    module: 'Printing',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'GST invoice with multiple tax rates.',
    tags: ['printing', 'gst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Print a GST invoice with CGST and SGST', expected_result: 'Printed receipt shows: Item, Qty, Rate, CGST %, CGST Amt, SGST %, SGST Amt, Total' },
    ],
  },
  {
    title: 'Custom print template fields are reflected in output',
    module: 'Printing',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Custom template configured with "Thank You for Shopping!" footer.',
    tags: ['printing', 'template', 'settings'],
    is_regression: false,
    steps: [
      { description: 'Print invoice after configuring custom footer', expected_result: 'Receipt footer shows "Thank You for Shopping!" as configured' },
    ],
  },
  {
    title: 'Print duplicate copy labeled "DUPLICATE"',
    module: 'Printing',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Already printed invoice.',
    tags: ['printing', 'duplicate', 'invoice'],
    is_regression: false,
    steps: [
      { description: 'Reprint an already-printed invoice', expected_result: 'Duplicate print clearly labeled "DUPLICATE COPY" at top to prevent fraud' },
    ],
  },
  {
    title: 'Barcode prints correctly on product labels',
    module: 'Printing',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Label printer configured. Product with barcode.',
    tags: ['printing', 'barcode', 'labels'],
    is_regression: false,
    steps: [
      { description: 'Print product barcode label', expected_result: 'Label prints with barcode, product name, and price. Barcode is scannable.' },
    ],
  },
  {
    title: 'Low paper warning shown when printer reports low paper',
    module: 'Printing',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Printer with low paper sensor. Paper nearly empty.',
    tags: ['printing', 'warning', 'ux'],
    is_regression: false,
    steps: [
      { description: 'Attempt print with very low paper', expected_result: 'Warning: "Printer paper low. Please refill." Shown before or during print attempt.' },
    ],
  },

  // ─── GST (15) ──────────────────────────────────────────────────────────
  {
    title: 'GST rate applied correctly on invoice for 5% rate product',
    module: 'GST',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Product with GST 5% and selling price ₹100.',
    tags: ['gst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create sale of 1 unit at ₹100 + 5% GST (intrastate)', expected_result: 'CGST = ₹2.50, SGST = ₹2.50, Total = ₹105' },
    ],
  },
  {
    title: 'GSTR-1 report includes all B2B sales with GSTIN',
    module: 'GST',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'B2B sales made to GST-registered customers this month.',
    tags: ['gst', 'gstr1', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > GSTR-1 for current month', expected_result: 'B2B section lists each sale with: Customer GSTIN, Invoice no., Date, Taxable Value, GST amount' },
    ],
  },
  {
    title: 'GSTR-2 report shows all purchases with ITC',
    module: 'GST',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Purchases from GST-registered suppliers this month.',
    tags: ['gst', 'gstr2', 'itc', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > GSTR-2', expected_result: 'All purchase invoices listed with Supplier GSTIN, Invoice details, Taxable value, ITC (CGST/SGST/IGST)' },
    ],
  },
  {
    title: 'Composite supply GST calculated on total bundle price',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Composite supply configured (e.g., food + service).',
    tags: ['gst', 'composite'],
    is_regression: false,
    steps: [
      { description: 'Create invoice for composite supply at ₹500', expected_result: 'GST applied on ₹500 total at single composite rate, not split by component' },
    ],
  },
  {
    title: 'HSN code mandatory for products above ₹500 turnover threshold',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Business turnover above threshold requiring HSN codes.',
    tags: ['gst', 'hsn', 'validation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to save product without HSN code when business is above threshold', expected_result: 'Warning: "HSN code required for your business turnover. Add HSN code." Configurable as mandatory.' },
    ],
  },
  {
    title: 'Reverse charge mechanism flagged on eligible purchases',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Purchase from unregistered supplier exceeding RCM threshold.',
    tags: ['gst', 'rcm', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create purchase from unregistered supplier for ₹6,000', expected_result: 'Purchase marked as RCM applicable. GST liability recorded as payable (not ITC claimable from supplier).' },
    ],
  },
  {
    title: 'Mixed GST rate invoice calculates each rate correctly',
    module: 'GST',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Products with 5%, 12%, and 18% GST.',
    tags: ['gst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create invoice with: Product A (5% GST, ₹100), Product B (12% GST, ₹200), Product C (18% GST, ₹50)', expected_result: 'Invoice shows separate GST for each rate: 5% on ₹100 = ₹5, 12% on ₹200 = ₹24, 18% on ₹50 = ₹9. Total GST = ₹38.' },
    ],
  },
  {
    title: 'E-invoice QR code generated for B2B above ₹5 Cr threshold',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Business turnover > ₹5 Cr. B2B sale > ₹50,000.',
    tags: ['gst', 'e-invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create qualifying B2B invoice', expected_result: 'E-invoice generated with IRN (Invoice Reference Number) and QR code. Both visible on printed invoice.' },
    ],
  },
  {
    title: 'GST mismatch between configured rate and invoice is flagged',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Product GST = 18%. Manual override attempted to 5%.',
    tags: ['gst', 'negative', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Override GST rate to 5% on product configured as 18% on invoice', expected_result: 'Warning: "GST rate overridden from 18% to 5%. This may cause GSTR mismatch. Confirm?"' },
    ],
  },
  {
    title: 'Tax-exempt (nil-rated) transactions recorded separately in GSTR',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Nil-rated products exist and sold.',
    tags: ['gst', 'exempt', 'gstr1', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Sell nil-rated product and generate GSTR-1', expected_result: 'Nil-rated sales appear in "Nil/Exempt Supplies" section of GSTR-1 separately from taxable supplies' },
    ],
  },
  {
    title: 'GST summary dashboard shows monthly liability correctly',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Sales and purchases with GST for current month.',
    tags: ['gst', 'dashboard', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > GST Dashboard', expected_result: 'Shows: Output Tax (from sales), Input Tax Credit (from purchases), Net Payable = Output - ITC' },
    ],
  },
  {
    title: 'GSTR-3B figures reconcile with GSTR-1 and GSTR-2',
    module: 'GST',
    priority: 'critical',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Sales and purchases for the month.',
    tags: ['gst', 'gstr3b', 'reconciliation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Generate GSTR-3B and compare to GSTR-1 output tax and GSTR-2 ITC', expected_result: 'GSTR-3B output tax matches GSTR-1 total. ITC in GSTR-3B matches GSTR-2 total.' },
    ],
  },
  {
    title: 'Customer GSTIN validated against state code',
    module: 'GST',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Add customer form with GSTIN field.',
    tags: ['gst', 'validation', 'customer'],
    is_regression: false,
    steps: [
      { description: 'Enter GSTIN starting with state code 29 (Karnataka) for customer in Maharashtra', expected_result: 'Warning: "GSTIN state code (29-Karnataka) does not match customer state (Maharashtra). Verify before saving."' },
    ],
  },
  {
    title: 'GST report export to Excel with correct column formatting',
    module: 'GST',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'GST data for current period.',
    tags: ['gst', 'export', 'excel'],
    is_regression: false,
    steps: [
      { description: 'Export GSTR-1 to Excel', expected_result: 'Excel file with: GSTIN in text format (not scientific notation), amounts as numbers, dates formatted DD/MM/YYYY' },
    ],
  },
  {
    title: 'Credit note reduces GST liability in GSTR-1',
    module: 'GST',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Sale with GST exists. Return/credit note created.',
    tags: ['gst', 'credit-note', 'gstr1', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Issue credit note for ₹500 sale with 18% GST', expected_result: 'GSTR-1 shows credit note in CDNR section. Output tax liability reduces by ₹90 (₹500 × 18%).' },
    ],
  },

  // ─── INVOICE (20) ──────────────────────────────────────────────────────
  {
    title: 'Invoice created from sale has all mandatory fields',
    module: 'Invoice',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Sale completed.',
    tags: ['smoke', 'regression', 'invoice'],
    is_regression: true,
    steps: [
      { description: 'Complete sale and view generated invoice', expected_result: 'Invoice shows: Invoice No., Date, Business Name, GSTIN, Customer details, Item list, Subtotal, GST breakup, Total, Payment mode, QR code (if configured)' },
    ],
  },
  {
    title: 'Invoice numbering resets at financial year start if configured',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Auto-reset on April 1st configured.',
    tags: ['invoice', 'numbering', 'regression'],
    is_regression: true,
    steps: [
      { description: 'First invoice after April 1st (new financial year)', expected_result: 'Invoice number resets to configured start (e.g., INV-2025-0001)' },
    ],
  },
  {
    title: 'Invoice PDF shared via email reaches recipient',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Invoice exists. Customer email available.',
    tags: ['invoice', 'email', 'sharing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap "Email Invoice" from invoice detail', expected_result: 'Email sent to customer with PDF attachment. Subject: "Invoice [No.] from [Business Name]"' },
    ],
  },
  {
    title: 'Proforma invoice converts to tax invoice on confirmation',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Proforma invoice feature enabled.',
    tags: ['invoice', 'proforma', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create proforma invoice for customer', expected_result: 'Document labeled "PROFORMA INVOICE". Not counted in revenue.' },
      { description: 'Convert proforma to tax invoice on payment', expected_result: 'Tax invoice created with new invoice number. Revenue recorded. Proforma closed.' },
    ],
  },
  {
    title: 'Invoice edit is blocked after payment is collected',
    module: 'Invoice',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Invoice with paid status.',
    tags: ['invoice', 'negative', 'security', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to edit item on a fully paid invoice', expected_result: '"Invoice cannot be edited after payment is collected. Cancel and recreate to make changes." Edit button disabled or shows warning.' },
    ],
  },
  {
    title: 'Invoice cancellation records reason and marks invoice CANCELLED',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Unpaid invoice exists.',
    tags: ['invoice', 'cancel', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Cancel invoice and enter reason: "Customer changed mind"', expected_result: 'Invoice status → CANCELLED. Reason logged. Stock restored. Not counted in revenue.' },
    ],
  },
  {
    title: 'Invoice with partial payment shows outstanding amount',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Invoice ₹1,000 with ₹600 paid.',
    tags: ['invoice', 'partial-payment', 'regression'],
    is_regression: true,
    steps: [
      { description: 'View invoice detail', expected_result: 'Invoice shows: Total ₹1,000, Paid ₹600, Outstanding ₹400, Status: Partially Paid' },
    ],
  },
  {
    title: 'Invoice search by customer name finds all their invoices',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Multiple invoices for customer "Ravi Kumar".',
    tags: ['invoice', 'search', 'customers'],
    is_regression: false,
    steps: [
      { description: 'Search invoices by customer name "Ravi Kumar"', expected_result: 'All invoices for Ravi Kumar listed' },
    ],
  },
  {
    title: 'Invoice with advance payment shows correct balance due',
    module: 'Invoice',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer paid ₹500 advance. Invoice total ₹2,000.',
    tags: ['invoice', 'advance', 'payment', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Apply advance payment to invoice', expected_result: 'Invoice shows: Total ₹2,000, Advance Applied ₹500, Balance Due ₹1,500' },
    ],
  },
  {
    title: 'Bulk invoice PDF download for date range',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Multiple invoices for this month.',
    tags: ['invoice', 'bulk', 'export', 'pdf'],
    is_regression: false,
    steps: [
      { description: 'Select date range and tap "Download All (PDF)"', expected_result: 'ZIP file with all invoice PDFs for the period downloaded' },
    ],
  },
  {
    title: 'Invoice due date reminder auto-sends to customer',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Invoice payment due tomorrow. Auto-reminder enabled.',
    tags: ['invoice', 'reminder', 'notifications'],
    is_regression: false,
    steps: [
      { description: 'Day before invoice due date', expected_result: 'Customer receives WhatsApp/email: "Invoice [No.] for ₹X is due tomorrow. Pay now: [link]"' },
    ],
  },
  {
    title: 'Recurring invoice generates on schedule',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Recurring invoice configured: monthly on 1st, customer "ABC Corp", ₹5,000.',
    tags: ['invoice', 'recurring', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On 1st of month, open app', expected_result: 'Invoice automatically created for ABC Corp, ₹5,000, with new invoice number' },
    ],
  },
  {
    title: 'Invoice PDF shows payment QR code for UPI',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'UPI QR configured in Settings.',
    tags: ['invoice', 'upi', 'qr-code'],
    is_regression: false,
    steps: [
      { description: 'Print or view invoice PDF', expected_result: 'UPI payment QR code visible on invoice. Customer can scan to pay.' },
    ],
  },
  {
    title: 'Large invoice with 100 line items renders correctly',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: '100 different products added to cart.',
    tags: ['invoice', 'edge-case', 'performance'],
    is_regression: false,
    steps: [
      { description: 'Create invoice with 100 line items', expected_result: 'Invoice created. PDF generated with all 100 items across multiple pages. Totals correct.' },
    ],
  },
  {
    title: 'Invoice listing is sorted by date descending by default',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Multiple invoices on different dates.',
    tags: ['invoice', 'sorting', 'ui'],
    is_regression: false,
    steps: [
      { description: 'Open invoice list without applying any filter', expected_result: 'Most recent invoice shown at top. Oldest at bottom.' },
    ],
  },
  {
    title: 'Invoice total with multiple discounts and GST is accurate',
    module: 'Invoice',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Products with GST. Item discount + invoice discount both applied.',
    tags: ['invoice', 'gst', 'discount', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create: Item ₹1,000 with 10% item discount, then 5% invoice discount, GST 18%', expected_result: 'After 10% item discount: ₹900. After 5% invoice discount: ₹855. GST 18% on ₹855 = ₹153.90. Total = ₹1,008.90' },
    ],
  },
  {
    title: 'Invoice with round-off shows correct round-off amount',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Round-off enabled in Settings.',
    tags: ['invoice', 'round-off', 'gst'],
    is_regression: false,
    steps: [
      { description: 'Create invoice with total ₹1,234.57 with round-off enabled', expected_result: 'Invoice shows: Subtotal ₹1,234.57, Round Off ₹0.43, Net Total ₹1,235.00' },
    ],
  },
  {
    title: 'Invoice in foreign currency shows correct exchange rate',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Multi-currency enabled. Exchange rate configured.',
    tags: ['invoice', 'currency', 'international'],
    is_regression: false,
    steps: [
      { description: 'Create invoice in USD for international customer', expected_result: 'Invoice shows USD amount, exchange rate used, and INR equivalent for accounting' },
    ],
  },
  {
    title: 'Invoice history is immutable – cannot delete finalized invoices',
    module: 'Invoice',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Finalized/paid invoice exists.',
    tags: ['invoice', 'audit', 'security', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Try to delete a finalized invoice (not cancel, but permanent delete)', expected_result: 'Delete option not available for finalized invoices. Only Void/Cancel with audit trail is allowed.' },
    ],
  },
  {
    title: 'Invoice summary statistics show correct counts and totals',
    module: 'Invoice',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Various invoices in different statuses.',
    tags: ['invoice', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'View invoice summary for this month', expected_result: 'Shows: Total Invoices, Paid, Partially Paid, Outstanding, Cancelled — with counts and amounts for each' },
    ],
  },

  // ─── ANALYTICS (10) ────────────────────────────────────────────────────
  {
    title: 'Analytics dashboard shows sales trend for last 30 days',
    module: 'Analytics',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Sales data for last 30 days.',
    tags: ['analytics', 'dashboard', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Analytics > Sales Trend', expected_result: 'Line chart shows daily sales for last 30 days. Peaks and troughs visible.' },
    ],
  },
  {
    title: 'Top 10 products by revenue chart is accurate',
    module: 'Analytics',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Sales data across multiple products.',
    tags: ['analytics', 'products', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Analytics > Top Products by Revenue', expected_result: 'Bar chart shows top 10 products. #1 product has highest revenue value. Cross-verify with reports.' },
    ],
  },
  {
    title: 'Customer acquisition trend shows new vs returning customers',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Mix of new and returning customers.',
    tags: ['analytics', 'customers', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Analytics > Customer Insights', expected_result: 'Stacked bar or pie chart shows new vs returning customer ratio per week/month' },
    ],
  },
  {
    title: 'Gross margin analysis shows margin per product category',
    module: 'Analytics',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Products with purchase and selling prices. Sales history.',
    tags: ['analytics', 'margin', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Analytics > Profit Margin by Category', expected_result: 'Each category shows: Revenue, COGS, Gross Profit, Margin %. Sorted by margin.' },
    ],
  },
  {
    title: 'Peak hours analysis shows busiest sales hours',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Sales distributed across different times of day.',
    tags: ['analytics', 'heatmap'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Analytics > Peak Hours', expected_result: 'Heatmap or bar chart shows sales volume by hour. Busiest hour highlighted.' },
    ],
  },
  {
    title: 'Analytics date range filter changes all charts simultaneously',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Analytics dashboard open.',
    tags: ['analytics', 'filter', 'ui', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Change date range from "Last 30 days" to "Last 7 days"', expected_result: 'All charts and KPIs on analytics page refresh to show data for last 7 days only' },
    ],
  },
  {
    title: 'Analytics compares current vs previous period',
    module: 'Analytics',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Sales data for current and previous period.',
    tags: ['analytics', 'comparison', 'regression'],
    is_regression: true,
    steps: [
      { description: 'View analytics with "vs previous period" toggle ON', expected_result: 'Each KPI shows: current value, previous value, % change (green/red arrow for up/down)' },
    ],
  },
  {
    title: 'Inventory turnover ratio calculated correctly',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Sales and inventory data available.',
    tags: ['analytics', 'inventory', 'kpi'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Analytics > Inventory Turnover', expected_result: 'Turnover ratio = COGS / Avg Inventory shown per product. Fast movers highlighted.' },
    ],
  },
  {
    title: 'Analytics export to PDF maintains chart readability',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Analytics data available.',
    tags: ['analytics', 'export', 'pdf'],
    is_regression: false,
    steps: [
      { description: 'Export analytics report to PDF', expected_result: 'PDF includes charts (not blank), data tables, date range header. Charts legible in print.' },
    ],
  },
  {
    title: 'Analytics with no data shows onboarding prompt',
    module: 'Analytics',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Fresh account with no transactions.',
    tags: ['analytics', 'empty-state', 'onboarding'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Analytics on account with no data', expected_result: 'Empty state: "No data yet. Start making sales to see your business analytics." with CTA to POS.' },
    ],
  },
];
