// Part 1: Modules, Release, Auth/Dashboard/Products/Inventory/Sales test cases

import type { SupabaseClient } from '@supabase/supabase-js';

export const MODULES = [
  { name: 'Authentication', description: 'User login, registration, password management, session handling, and access control' },
  { name: 'Dashboard', description: 'Home screen KPIs, quick actions, sales summary, low stock alerts, and recent activity feed' },
  { name: 'Products', description: 'Product catalog management including add, edit, delete, barcode, pricing, GST, and variants' },
  { name: 'Inventory', description: 'Stock tracking, adjustments, transfers, low-stock alerts, and valuation reports' },
  { name: 'Sales', description: 'Point-of-sale billing, cart management, discounts, payment collection, and receipt generation' },
  { name: 'Purchase', description: 'Purchase orders, GRN, supplier invoices, payment tracking, and purchase returns' },
  { name: 'Suppliers', description: 'Supplier directory, contact details, purchase history, credit terms, and ledger' },
  { name: 'Customers', description: 'Customer profiles, purchase history, credit management, loyalty points, and communication' },
  { name: 'Expenses', description: 'Business expense recording, categorization, approvals, and expense reports' },
  { name: 'Reports', description: 'Sales, purchase, inventory, GST, profit & loss, and custom report generation' },
  { name: 'Subscription', description: 'Plan management, billing cycles, feature gating, trial periods, and renewals' },
  { name: 'Settings', description: 'Business profile, tax configuration, payment modes, print settings, and preferences' },
  { name: 'Profile', description: 'User account details, password change, notification preferences, and activity log' },
  { name: 'Cloud Sync', description: 'Real-time data synchronization across devices, conflict resolution, and sync status' },
  { name: 'Notifications', description: 'In-app notifications, push alerts, low-stock warnings, and payment reminders' },
  { name: 'Search', description: 'Global search across products, customers, invoices, and transactions' },
  { name: 'Backup & Restore', description: 'Manual and scheduled backup creation, download, upload, and data restoration' },
  { name: 'Security', description: 'PIN lock, biometric auth, role-based access control, audit logs, and data encryption' },
  { name: 'Performance', description: 'App startup time, list rendering, report generation speed, and memory usage' },
  { name: 'Offline Mode', description: 'Offline data access, local transactions, sync queue management, and conflict handling' },
  { name: 'Database', description: 'Local SQLite integrity, migration versioning, data consistency, and query performance' },
  { name: 'API', description: 'REST API endpoints, authentication headers, rate limiting, error responses, and data contracts' },
  { name: 'Printing', description: 'Bluetooth/WiFi thermal printer pairing, invoice printing, and print template configuration' },
  { name: 'GST', description: 'GST rate configuration, CGST/SGST/IGST calculation, HSN codes, and GSTR report generation' },
  { name: 'Invoice', description: 'Invoice creation, numbering, editing, cancellation, sharing, and payment tracking' },
  { name: 'Analytics', description: 'Sales trends, top products, customer insights, profit margins, and business health metrics' },
];

export type TestCaseDef = {
  title: string;
  module: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  estimated_minutes: number;
  is_automation_ready: boolean;
  preconditions: string;
  tags: string[];
  is_regression: boolean;
  steps: Array<{ description: string; expected_result: string; notes?: string }>;
};

export const TEST_CASES_PART1: TestCaseDef[] = [
  // ─── AUTHENTICATION (15) ───────────────────────────────────────────────
  {
    title: 'Login with valid email and password',
    module: 'Authentication',
    priority: 'critical',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'App installed. Valid admin account exists with email admin@craftx.in and known password.',
    tags: ['smoke', 'regression', 'auth', 'login'],
    is_regression: true,
    steps: [
      { description: 'Launch RetailManager app', expected_result: 'Login screen is displayed with email and password fields' },
      { description: 'Enter email: admin@craftx.in', expected_result: 'Email field accepts input, no validation error shown' },
      { description: 'Enter valid password', expected_result: 'Password is masked with dots' },
      { description: 'Tap "Login" button', expected_result: 'Loading indicator appears briefly, then Dashboard screen loads' },
    ],
  },
  {
    title: 'Login with invalid password shows error',
    module: 'Authentication',
    priority: 'critical',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'App installed. Valid account exists.',
    tags: ['regression', 'auth', 'negative', 'login'],
    is_regression: true,
    steps: [
      { description: 'Enter valid email: admin@craftx.in', expected_result: 'Email accepted' },
      { description: 'Enter incorrect password: WrongPass@999', expected_result: 'Password field accepts input' },
      { description: 'Tap "Login" button', expected_result: 'Error message "Invalid email or password" is shown. No navigation occurs.' },
    ],
  },
  {
    title: 'Login with empty email field shows validation',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'App on login screen.',
    tags: ['auth', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Leave email field blank', expected_result: 'Email field is empty' },
      { description: 'Enter any password', expected_result: 'Password field has value' },
      { description: 'Tap "Login"', expected_result: 'Inline error "Email is required" appears below email field' },
    ],
  },
  {
    title: 'Login with malformed email shows validation',
    module: 'Authentication',
    priority: 'medium',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'App on login screen.',
    tags: ['auth', 'validation', 'negative', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Enter malformed email: notanemail', expected_result: 'Email field accepts input' },
      { description: 'Enter any password and tap Login', expected_result: 'Inline error "Please enter a valid email address" shown. Login not attempted.' },
    ],
  },
  {
    title: 'Forgot password sends reset email',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Valid account exists with registered email.',
    tags: ['auth', 'password-reset', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap "Forgot Password?" link on login screen', expected_result: 'Forgot Password screen opens with email input' },
      { description: 'Enter registered email: admin@craftx.in', expected_result: 'Email accepted' },
      { description: 'Tap "Send Reset Link"', expected_result: 'Success message "Reset link sent to admin@craftx.in" is displayed' },
      { description: 'Check email inbox', expected_result: 'Email with password reset link arrives within 2 minutes', notes: 'Manual check required' },
    ],
  },
  {
    title: 'Session persists after app restart',
    module: 'Authentication',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'User is logged in.',
    tags: ['auth', 'session', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Log in successfully', expected_result: 'Dashboard visible' },
      { description: 'Force-close the app', expected_result: 'App closes' },
      { description: 'Relaunch the app', expected_result: 'App opens directly to Dashboard without prompting login again' },
    ],
  },
  {
    title: 'Logout clears session and redirects to login',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'User is logged in.',
    tags: ['auth', 'logout', 'regression', 'smoke'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Profile > Logout', expected_result: 'Logout confirmation dialog appears' },
      { description: 'Confirm logout', expected_result: 'Session is cleared and Login screen is shown' },
      { description: 'Press back button', expected_result: 'App does not navigate back to Dashboard — user remains on Login screen' },
    ],
  },
  {
    title: 'Multiple failed logins triggers account lockout warning',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Valid account exists. Security policy: 5 failed attempts = warning.',
    tags: ['auth', 'security', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt login with wrong password 5 consecutive times', expected_result: 'Each attempt shows "Invalid email or password"' },
      { description: 'Observe UI after 5th failed attempt', expected_result: 'Warning message "Too many failed attempts. Try again in 15 minutes." is displayed' },
    ],
  },
  {
    title: 'PIN lock activates after configured idle timeout',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'PIN lock enabled in Security settings. Idle timeout set to 1 minute.',
    tags: ['auth', 'security', 'pin', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Log in and remain idle for 1 minute', expected_result: 'PIN entry screen appears, overlaying the last screen' },
      { description: 'Enter correct PIN', expected_result: 'App unlocks and returns to the previous screen without data loss' },
    ],
  },
  {
    title: 'Biometric login unlocks app successfully',
    module: 'Authentication',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Biometric (fingerprint/face) configured on device. Biometric login enabled in app settings.',
    tags: ['auth', 'biometric', 'regression'],
    is_regression: true,
    steps: [
      { description: 'App is on PIN/biometric prompt screen', expected_result: 'Biometric prompt shown' },
      { description: 'Authenticate using enrolled fingerprint or Face ID', expected_result: 'App unlocks immediately without PIN entry' },
    ],
  },
  {
    title: 'Password change with correct current password succeeds',
    module: 'Authentication',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'User is logged in. Current password is known.',
    tags: ['auth', 'password-change'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Profile > Change Password', expected_result: 'Change Password screen opens' },
      { description: 'Enter current password correctly', expected_result: 'Current password field accepts input' },
      { description: 'Enter new password: NewPass@2025 and confirm it', expected_result: 'Both new password fields match' },
      { description: 'Tap "Update Password"', expected_result: 'Success toast "Password updated successfully" shown. Session remains active.' },
    ],
  },
  {
    title: 'New password must meet complexity requirements',
    module: 'Authentication',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'User on Change Password screen.',
    tags: ['auth', 'validation', 'negative', 'password-change'],
    is_regression: false,
    steps: [
      { description: 'Enter weak new password: abc', expected_result: 'Password field accepts input' },
      { description: 'Tap Update Password', expected_result: 'Validation error: "Password must be at least 8 characters and include uppercase, number, and symbol"' },
    ],
  },
  {
    title: 'Expired JWT token forces re-login',
    module: 'Authentication',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'User is logged in. Token expiry is known (e.g., 1 hour). Wait for expiry or simulate via test account.',
    tags: ['auth', 'security', 'jwt', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Let the JWT access token expire', expected_result: 'Token is no longer valid on server' },
      { description: 'Perform any authenticated action (e.g., load products)', expected_result: 'App detects 401 response, shows "Session expired. Please log in again." and navigates to Login screen.' },
    ],
  },
  {
    title: 'Login with 500-character password does not crash app',
    module: 'Authentication',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'App on login screen.',
    tags: ['auth', 'edge-case', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Paste a 500-character string into the password field', expected_result: 'Field accepts input (may truncate at UI level)' },
      { description: 'Tap Login', expected_result: 'App shows authentication error without crashing' },
    ],
  },
  {
    title: 'Unauthorized user cannot access admin-only screens',
    module: 'Authentication',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Staff-role account exists (non-admin). Staff is logged in.',
    tags: ['auth', 'authorization', 'rbac', 'security', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Log in as staff user', expected_result: 'Dashboard loads with restricted navigation' },
      { description: 'Attempt to navigate to Settings > Business Profile', expected_result: '"Access denied" message or option is hidden based on RBAC policy' },
      { description: 'Attempt to access Reports > Financial Summary', expected_result: 'Access is blocked or section is not visible to staff role' },
    ],
  },

  // ─── DASHBOARD (10) ────────────────────────────────────────────────────
  {
    title: 'Dashboard loads with correct today sales summary',
    module: 'Dashboard',
    priority: 'critical',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'User logged in. At least one sale made today.',
    tags: ['smoke', 'regression', 'dashboard', 'kpi'],
    is_regression: true,
    steps: [
      { description: 'Open app and navigate to Dashboard', expected_result: 'Dashboard loads within 2 seconds' },
      { description: 'Observe "Today\'s Sales" KPI card', expected_result: 'Shows correct total matching sum of today\'s completed sales' },
    ],
  },
  {
    title: 'Low stock alert shows products below reorder level',
    module: 'Dashboard',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'At least 2 products have stock quantity below their configured reorder level.',
    tags: ['dashboard', 'inventory', 'alerts', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Dashboard', expected_result: 'Dashboard visible' },
      { description: 'Scroll to "Low Stock Alerts" section', expected_result: 'Section displays list of products below reorder level with current stock count' },
      { description: 'Tap a low-stock product in the list', expected_result: 'App navigates to that product\'s detail screen' },
    ],
  },
  {
    title: 'Dashboard quick action "New Sale" navigates to POS',
    module: 'Dashboard',
    priority: 'high',
    estimated_minutes: 2,
    is_automation_ready: true,
    preconditions: 'User logged in.',
    tags: ['smoke', 'dashboard', 'navigation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap "New Sale" quick action button on Dashboard', expected_result: 'POS/Sales screen opens immediately' },
    ],
  },
  {
    title: 'Dashboard shows correct pending purchase orders count',
    module: 'Dashboard',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'At least 3 purchase orders in "Pending" status.',
    tags: ['dashboard', 'purchase', 'kpi'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Dashboard', expected_result: 'Dashboard loads' },
      { description: 'Observe "Pending POs" KPI card', expected_result: 'Count matches exact number of pending purchase orders in system' },
    ],
  },
  {
    title: 'Dashboard recent activity feed shows latest 10 transactions',
    module: 'Dashboard',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'At least 10 transactions exist (sales/purchases).',
    tags: ['dashboard', 'activity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open Dashboard and scroll to Recent Activity section', expected_result: 'List of up to 10 most recent transactions shown in reverse chronological order' },
      { description: 'Tap any activity entry', expected_result: 'Navigates to the relevant transaction detail screen' },
    ],
  },
  {
    title: 'Dashboard KPIs update after completing a sale',
    module: 'Dashboard',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'User logged in. Note current Dashboard "Today\'s Sales" value.',
    tags: ['dashboard', 'regression', 'integration'],
    is_regression: true,
    steps: [
      { description: 'Note Today\'s Sales value on Dashboard', expected_result: 'Value recorded (e.g., ₹12,500)' },
      { description: 'Complete a new sale of ₹500', expected_result: 'Sale recorded successfully' },
      { description: 'Return to Dashboard', expected_result: 'Today\'s Sales updates to previous value + ₹500 (e.g., ₹13,000)' },
    ],
  },
  {
    title: 'Dashboard renders correctly on tablet (landscape)',
    module: 'Dashboard',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'App running on tablet device or emulator in landscape orientation.',
    tags: ['dashboard', 'responsive', 'ui', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Open app on tablet in landscape mode', expected_result: 'Dashboard layout adapts to wider screen, KPI cards arranged in multi-column grid' },
      { description: 'Rotate to portrait', expected_result: 'Layout reflows without overflow or truncation' },
    ],
  },
  {
    title: 'Dashboard loads within 2 seconds with 100,000 products',
    module: 'Dashboard',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Database seeded with 100,000 product records.',
    tags: ['dashboard', 'performance', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Log in and navigate to Dashboard with large dataset', expected_result: 'Dashboard renders within 2 seconds. KPI values correct.' },
      { description: 'Scroll through the screen', expected_result: 'No jank or freeze. Scroll is smooth.' },
    ],
  },
  {
    title: 'Dashboard shows correct currency symbol per business settings',
    module: 'Dashboard',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Business currency set to INR (₹) in Settings.',
    tags: ['dashboard', 'settings', 'localization'],
    is_regression: false,
    steps: [
      { description: 'Open Dashboard', expected_result: 'All monetary KPIs display ₹ symbol before the value' },
      { description: 'Change currency to USD in Settings', expected_result: 'Dashboard now shows $ before all monetary values' },
    ],
  },
  {
    title: 'Dashboard offline state shows last cached data with offline banner',
    module: 'Dashboard',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'User logged in. Data loaded at least once.',
    tags: ['dashboard', 'offline', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Disable device internet connection', expected_result: 'Connection lost' },
      { description: 'Navigate to Dashboard', expected_result: 'Dashboard loads with last cached values. Offline banner "You are offline – showing cached data" displayed at top.' },
    ],
  },

  // ─── PRODUCTS (30) ─────────────────────────────────────────────────────
  {
    title: 'Add new product with all mandatory fields',
    module: 'Products',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'User logged in with Products access. At least one GST rate configured.',
    tags: ['smoke', 'regression', 'products', 'add'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Products and tap "Add Product"', expected_result: 'Add Product form opens' },
      { description: 'Enter Name: "Basmati Rice 5kg", Category: "Groceries", Purchase Price: 250, Selling Price: 310, GST: 5%, Unit: KG', expected_result: 'All fields accept input without errors' },
      { description: 'Tap "Save"', expected_result: 'Product created. Success toast shown. Product appears in list.' },
    ],
  },
  {
    title: 'Add product with barcode by scanning',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Camera permission granted. Physical barcode available for scanning.',
    tags: ['products', 'barcode', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On Add Product form, tap the barcode icon', expected_result: 'Camera opens in barcode scan mode' },
      { description: 'Scan a valid EAN-13 barcode', expected_result: 'Barcode number auto-populates the barcode field' },
      { description: 'Complete remaining fields and save', expected_result: 'Product saved with barcode value correctly stored' },
    ],
  },
  {
    title: 'Edit existing product selling price',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'At least one product exists.',
    tags: ['products', 'edit', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap a product from the list', expected_result: 'Product detail screen opens' },
      { description: 'Tap "Edit" and change Selling Price from 310 to 325', expected_result: 'Field updated' },
      { description: 'Save the product', expected_result: 'Updated price saved. Product list reflects new price.' },
    ],
  },
  {
    title: 'Delete product moves it to inactive state',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'At least one product with zero stock exists.',
    tags: ['products', 'delete', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Long-press a product and select "Delete"', expected_result: 'Confirmation dialog appears: "Delete product? This cannot be undone."' },
      { description: 'Confirm deletion', expected_result: 'Product is removed from active list. Does not appear in POS search.' },
    ],
  },
  {
    title: 'Cannot delete product with existing stock',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product exists with stock quantity > 0.',
    tags: ['products', 'delete', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt to delete product that has stock > 0', expected_result: 'Error dialog: "Cannot delete product with existing stock. Adjust inventory to zero first."' },
    ],
  },
  {
    title: 'Duplicate product name within same category shows error',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product "Basmati Rice 5kg" already exists.',
    tags: ['products', 'negative', 'validation', 'duplicate'],
    is_regression: false,
    steps: [
      { description: 'Try to add a new product with name "Basmati Rice 5kg" in same category', expected_result: 'Validation error: "Product with this name already exists in this category"' },
    ],
  },
  {
    title: 'Product with 500-character name is rejected',
    module: 'Products',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'edge-case', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Paste a 500-character string into the Product Name field', expected_result: 'Field truncates input or shows "Name cannot exceed 100 characters"' },
    ],
  },
  {
    title: 'Product with Unicode name (Hindi) saves correctly',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'unicode', 'localization', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Enter product name: "बासमती चावल 5kg"', expected_result: 'Unicode name accepted in field' },
      { description: 'Save product', expected_result: 'Product saved and displayed correctly with Hindi characters' },
    ],
  },
  {
    title: 'Negative selling price is rejected',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'negative', 'validation', 'price'],
    is_regression: false,
    steps: [
      { description: 'Enter Selling Price: -100', expected_result: 'Inline error: "Price cannot be negative"' },
    ],
  },
  {
    title: 'Zero selling price is rejected',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'negative', 'validation', 'price'],
    is_regression: false,
    steps: [
      { description: 'Enter Selling Price: 0', expected_result: 'Inline error: "Selling price must be greater than zero" shown on save' },
    ],
  },
  {
    title: 'Product GST rate persists to invoice calculation',
    module: 'Products',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Product "Biscuit Pack" has GST rate 18% configured.',
    tags: ['products', 'gst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add "Biscuit Pack" to a sale cart with quantity 2 at ₹100 each', expected_result: 'Cart shows base price ₹200' },
      { description: 'Confirm GST calculation on invoice', expected_result: 'CGST 9% = ₹18, SGST 9% = ₹18, Total = ₹236' },
    ],
  },
  {
    title: 'Search products by name returns relevant results',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'At least 20 products exist.',
    tags: ['products', 'search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap search icon in Products list', expected_result: 'Search bar appears with keyboard' },
      { description: 'Type "rice"', expected_result: 'List filters to show only products with "rice" in name or description' },
      { description: 'Clear search', expected_result: 'Full product list restored' },
    ],
  },
  {
    title: 'Filter products by category',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Multiple categories exist with products.',
    tags: ['products', 'filter', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap Filter icon in Products', expected_result: 'Filter panel opens' },
      { description: 'Select category "Beverages"', expected_result: 'List shows only Beverages products' },
    ],
  },
  {
    title: 'Import products from CSV file',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Valid CSV file with required columns prepared (Name, Category, Price, GST).',
    tags: ['products', 'import', 'csv', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Products > Import', expected_result: 'Import screen opens' },
      { description: 'Select valid CSV file', expected_result: 'Preview shows parsed rows with mapped columns' },
      { description: 'Tap "Import"', expected_result: 'All valid rows imported. Summary shows "X imported, Y skipped".' },
    ],
  },
  {
    title: 'CSV import rejects rows with missing mandatory fields',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'CSV file with some rows missing "Price" column.',
    tags: ['products', 'import', 'negative', 'csv'],
    is_regression: false,
    steps: [
      { description: 'Import CSV with 5 rows where 2 are missing Selling Price', expected_result: 'Import completes. Summary: "3 imported, 2 skipped – reason: missing selling price". Skipped rows downloadable.' },
    ],
  },
  {
    title: 'Product barcode must be unique',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product with barcode 8901234567890 exists.',
    tags: ['products', 'barcode', 'negative', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Try to create another product with barcode 8901234567890', expected_result: 'Error: "Barcode already assigned to [existing product name]"' },
    ],
  },
  {
    title: 'Product list displays correctly with 10,000 items',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Database has 10,000 product records.',
    tags: ['products', 'performance', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Products list with 10,000 items', expected_result: 'List loads within 3 seconds. Virtualized list renders only visible items.' },
      { description: 'Scroll rapidly through the list', expected_result: 'No crash, no blank rows, scroll remains responsive' },
    ],
  },
  {
    title: 'Product with purchase price higher than selling price shows margin warning',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'pricing', 'validation', 'warning'],
    is_regression: false,
    steps: [
      { description: 'Enter Purchase Price: 500, Selling Price: 400', expected_result: 'Warning banner: "Selling price is below purchase price. Margin is negative." shown before save.' },
    ],
  },
  {
    title: 'Product variants (size/color) can be added and saved',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Product variants feature enabled.',
    tags: ['products', 'variants', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add product "T-Shirt" and navigate to Variants tab', expected_result: 'Variants section visible' },
      { description: 'Add variant: Size=M, Color=Blue, Price=599', expected_result: 'Variant row added' },
      { description: 'Add variant: Size=L, Color=Red, Price=649', expected_result: 'Second variant row added' },
      { description: 'Save product', expected_result: 'Product saved with 2 variants. Each variant shows its own stock tracking.' },
    ],
  },
  {
    title: 'HSN code saves and reflects in GST reports',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'GST enabled in business settings.',
    tags: ['products', 'gst', 'hsn', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add/edit product and enter HSN code: 1006', expected_result: 'HSN field accepts numeric input' },
      { description: 'Save product', expected_result: 'HSN saved correctly' },
      { description: 'Generate GSTR-1 report', expected_result: 'Product appears under HSN code 1006 in the report' },
    ],
  },
  {
    title: 'Product image can be added from gallery',
    module: 'Products',
    priority: 'low',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Storage permission granted.',
    tags: ['products', 'image', 'ui'],
    is_regression: false,
    steps: [
      { description: 'On Add/Edit Product, tap the image placeholder', expected_result: 'Gallery picker opens' },
      { description: 'Select an image from gallery', expected_result: 'Selected image displays as product thumbnail' },
      { description: 'Save product', expected_result: 'Image saved and visible in product list tile' },
    ],
  },
  {
    title: 'Product category management: add new category',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'User has access to product categories.',
    tags: ['products', 'category', 'settings'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Products > Categories > Add Category', expected_result: 'Category creation form opens' },
      { description: 'Enter name: "Dairy & Eggs" and save', expected_result: 'Category "Dairy & Eggs" created and available in product add/edit form' },
    ],
  },
  {
    title: 'Product reorder level can be configured per product',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product exists.',
    tags: ['products', 'inventory', 'reorder', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Edit a product and set Reorder Level: 10', expected_result: 'Field accepts integer value' },
      { description: 'Save product', expected_result: 'Reorder level saved. Product triggers low-stock alert when stock drops to 10.' },
    ],
  },
  {
    title: 'Product unit of measure options are configurable',
    module: 'Products',
    priority: 'low',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Units configured in Settings.',
    tags: ['products', 'settings', 'unit'],
    is_regression: false,
    steps: [
      { description: 'On Add Product, open Unit dropdown', expected_result: 'Available units shown: Nos, KG, Litre, Pack, Box, Piece, Dozen' },
      { description: 'Select "KG" and save', expected_result: 'Product saved with unit KG. Displayed correctly on invoices.' },
    ],
  },
  {
    title: 'Product discount percentage can be set per product',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Add Product form open.',
    tags: ['products', 'pricing', 'discount'],
    is_regression: false,
    steps: [
      { description: 'Enter Max Discount: 15%', expected_result: 'Field accepts value' },
      { description: 'Save and add product to sale', expected_result: 'In POS, discount allowed up to 15% for this product. Greater discount rejected.' },
    ],
  },
  {
    title: 'Product export to CSV contains all fields',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'At least 10 products exist.',
    tags: ['products', 'export', 'csv'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Products > Export', expected_result: 'Export option available' },
      { description: 'Tap Export CSV', expected_result: 'CSV file downloaded with columns: Name, Category, Barcode, Purchase Price, Selling Price, GST %, HSN, Unit, Stock, Reorder Level' },
    ],
  },
  {
    title: 'Inactive products do not appear in POS search',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product "Test Product X" marked as inactive.',
    tags: ['products', 'pos', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open POS/Sales screen and search for "Test Product X"', expected_result: 'Product does not appear in search results' },
    ],
  },
  {
    title: 'Product selling price displays correct inclusive GST total',
    module: 'Products',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Business configured for GST-inclusive pricing.',
    tags: ['products', 'gst', 'pricing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add product with selling price ₹118, GST 18%', expected_result: 'System shows base price = ₹100, GST = ₹18, Total = ₹118' },
    ],
  },
  {
    title: 'Product with stock = 0 shows "Out of Stock" badge',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Product exists with stock quantity = 0.',
    tags: ['products', 'inventory', 'ui', 'badge'],
    is_regression: false,
    steps: [
      { description: 'View Products list', expected_result: 'Product with zero stock displays "Out of Stock" badge/indicator' },
    ],
  },
  {
    title: 'Bulk price update applies to selected products',
    module: 'Products',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'At least 5 products in "Groceries" category.',
    tags: ['products', 'bulk', 'pricing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Select 5 products via checkboxes', expected_result: 'Multi-select toolbar appears' },
      { description: 'Tap "Bulk Edit" > Increase Price by 10%', expected_result: 'Confirmation: "Increase selling price of 5 products by 10%?"' },
      { description: 'Confirm', expected_result: 'All 5 products\' selling prices increased by 10%. Toast: "5 products updated."' },
    ],
  },

  // ─── INVENTORY (20) ────────────────────────────────────────────────────
  {
    title: 'Stock increases correctly after goods receipt note',
    module: 'Inventory',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Purchase order in "Ordered" status. Product "Sunflower Oil 1L" with current stock 10.',
    tags: ['smoke', 'regression', 'inventory', 'grn'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase Order for Sunflower Oil 1L (qty: 50)', expected_result: 'PO detail visible' },
      { description: 'Tap "Receive Goods" and enter received quantity: 50', expected_result: 'GRN form shows qty 50' },
      { description: 'Confirm GRN', expected_result: 'Stock for "Sunflower Oil 1L" increases from 10 to 60. PO status changes to "Received".' },
    ],
  },
  {
    title: 'Manual stock adjustment adds to current stock',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Product "Sugar 1KG" has stock = 25.',
    tags: ['inventory', 'adjustment', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Inventory > Stock Adjustment', expected_result: 'Adjustment screen opens' },
      { description: 'Search and select "Sugar 1KG"', expected_result: 'Product selected with current stock shown as 25' },
      { description: 'Enter adjustment: +15, reason: "Stock found in back storage"', expected_result: 'Form ready' },
      { description: 'Save adjustment', expected_result: 'Stock updates to 40. Adjustment log entry created with reason.' },
    ],
  },
  {
    title: 'Manual stock adjustment with negative quantity reduces stock',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Product has stock = 25.',
    tags: ['inventory', 'adjustment', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create stock adjustment of -10 for product with stock 25', expected_result: 'Adjustment saved. Stock becomes 15.' },
    ],
  },
  {
    title: 'Stock cannot go below zero via adjustment',
    module: 'Inventory',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product has stock = 5.',
    tags: ['inventory', 'negative', 'validation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Attempt adjustment of -10 on product with stock = 5', expected_result: 'Validation error: "Adjustment would result in negative stock. Current stock: 5, Adjustment: -10"' },
    ],
  },
  {
    title: 'Stock transfer between warehouses updates both locations',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 7,
    is_automation_ready: false,
    preconditions: 'Two warehouses configured: Main Store, Godown. "Cooking Oil 5L" stock: Main=20, Godown=50.',
    tags: ['inventory', 'transfer', 'warehouse', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Inventory > Stock Transfer', expected_result: 'Transfer form opens' },
      { description: 'From: Godown, To: Main Store, Product: Cooking Oil 5L, Qty: 10', expected_result: 'Form populated' },
      { description: 'Confirm transfer', expected_result: 'Godown stock: 40, Main Store stock: 30. Transfer record logged.' },
    ],
  },
  {
    title: 'Inventory valuation report shows correct FIFO value',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Valuation method set to FIFO in Settings.',
    tags: ['inventory', 'valuation', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Inventory > Valuation Report', expected_result: 'Report loads' },
      { description: 'Verify total inventory value matches FIFO cost method calculation', expected_result: 'Value matches expected FIFO calculation based on purchase history' },
    ],
  },
  {
    title: 'Low stock alert triggers notification at reorder level',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Product "Milk 500ml" has reorder level = 20, current stock = 25.',
    tags: ['inventory', 'alerts', 'notifications', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Complete a sale that reduces "Milk 500ml" stock to 19', expected_result: 'Sale succeeds' },
      { description: 'Check notification center', expected_result: 'Notification: "Low Stock Alert: Milk 500ml – Only 19 units remaining (Reorder level: 20)"' },
      { description: 'Check Dashboard low stock section', expected_result: 'Product appears in low-stock list' },
    ],
  },
  {
    title: 'Inventory stock count locks product for editing during count',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Active stock count session in progress.',
    tags: ['inventory', 'stock-count', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Start a stock count session', expected_result: 'Stock count screen opens with product list' },
      { description: 'Try to edit stock of a counted product from another screen', expected_result: 'Warning: "Stock count in progress. Product is locked for editing."' },
    ],
  },
  {
    title: 'Expiry date tracking shows expired products in alerts',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Products with expiry dates configured. One product expires today.',
    tags: ['inventory', 'expiry', 'alerts', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Inventory > Expiry Alerts', expected_result: 'List shows products expiring within 30 days, sorted by nearest expiry' },
      { description: 'Observe today\'s expired product', expected_result: 'Product highlighted in red with expiry date shown' },
    ],
  },
  {
    title: 'Stock movement history shows all in/out transactions',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Product with multiple transactions (sales, GRN, adjustments).',
    tags: ['inventory', 'history', 'audit'],
    is_regression: false,
    steps: [
      { description: 'Navigate to product > Stock Movement History', expected_result: 'Chronological list of all stock changes with date, type (Sale/GRN/Adjustment), quantity, and running balance' },
    ],
  },
  {
    title: 'Sale reduces product stock by exact quantity sold',
    module: 'Inventory',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Product "Pen Set" has stock = 100.',
    tags: ['smoke', 'regression', 'inventory', 'sales', 'integration'],
    is_regression: true,
    steps: [
      { description: 'Create sale with 5 units of "Pen Set"', expected_result: 'Sale completed successfully' },
      { description: 'Check inventory for "Pen Set"', expected_result: 'Stock reduced from 100 to 95' },
    ],
  },
  {
    title: 'Cannot sell product with zero stock (strict mode)',
    module: 'Inventory',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product "Stapler" has stock = 0. Settings: "Allow sale below zero stock" = OFF.',
    tags: ['inventory', 'sales', 'negative', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add "Stapler" to POS cart', expected_result: 'Warning: "Out of Stock: Stapler" shown. Product cannot be added to cart.' },
    ],
  },
  {
    title: 'Large quantity sale (10,000 units) processes correctly',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Product has stock >= 10,000.',
    tags: ['inventory', 'edge-case', 'performance'],
    is_regression: false,
    steps: [
      { description: 'Add product with quantity 10,000 to POS', expected_result: 'POS accepts large quantity without overflow or display issues' },
      { description: 'Complete sale', expected_result: 'Invoice generated correctly. Stock reduced by 10,000.' },
    ],
  },
  {
    title: 'Inventory report correctly shows opening and closing stock',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Multiple transactions in date range.',
    tags: ['inventory', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Inventory > Stock Report, select date range last 7 days', expected_result: 'Report shows: Opening Stock, In, Out, Closing Stock per product' },
      { description: 'Verify: Closing Stock = Opening + In - Out for each product', expected_result: 'Math checks out for all products' },
    ],
  },
  {
    title: 'Purchase return reduces supplier debt and restores stock',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 7,
    is_automation_ready: false,
    preconditions: 'Purchase order received with 100 units. 10 units found damaged.',
    tags: ['inventory', 'purchase', 'return', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Purchase > Return and create return for 10 units', expected_result: 'Return form accepts quantity 10' },
      { description: 'Save purchase return', expected_result: 'Stock reduces by 10. Supplier outstanding reduces by (10 × purchase price).' },
    ],
  },
  {
    title: 'Batch/lot number tracking creates traceable records',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 7,
    is_automation_ready: false,
    preconditions: 'Batch tracking enabled for product "Medicine A".',
    tags: ['inventory', 'batch', 'traceability'],
    is_regression: false,
    steps: [
      { description: 'Receive 100 units of Medicine A with batch no: MED-2025-001, expiry: 31-Dec-2026', expected_result: 'GRN records batch details' },
      { description: 'Sell 10 units', expected_result: 'Invoice includes batch number MED-2025-001' },
    ],
  },
  {
    title: 'Inventory adjustment reason is mandatory',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Stock Adjustment form open.',
    tags: ['inventory', 'validation', 'negative'],
    is_regression: false,
    steps: [
      { description: 'Enter adjustment quantity but leave reason blank', expected_result: 'Save rejected with error "Adjustment reason is required"' },
    ],
  },
  {
    title: 'Offline stock adjustment syncs when connectivity restored',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Device offline. Product stock locally = 50.',
    tags: ['inventory', 'offline', 'sync', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create stock adjustment of +20 while offline', expected_result: 'Local stock shows 70. Adjustment stored in sync queue.' },
      { description: 'Restore internet connection', expected_result: 'Adjustment syncs to server. Server stock = 70. No data loss.' },
    ],
  },
  {
    title: 'Inventory report can be exported to PDF',
    module: 'Inventory',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Inventory data exists.',
    tags: ['inventory', 'reports', 'export', 'pdf'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Inventory Report and tap "Export PDF"', expected_result: 'PDF generated and share dialog opens' },
      { description: 'Open generated PDF', expected_result: 'PDF is legible with correct data, headers, and page numbers' },
    ],
  },
  {
    title: 'Rapid successive stock adjustments do not create race condition',
    module: 'Inventory',
    priority: 'high',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Two devices logged into same account. Product stock = 100.',
    tags: ['inventory', 'concurrency', 'edge-case', 'security'],
    is_regression: false,
    steps: [
      { description: 'Device A reduces stock by 30 while Device B simultaneously reduces by 20', expected_result: 'After both adjustments sync, final stock = 50 (not 70 or 80 due to race condition)' },
    ],
  },

  // ─── SALES (35) ────────────────────────────────────────────────────────
  {
    title: 'Create sale with single product and collect cash payment',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'User logged in. Product "Biscuit" with stock > 0. Cash payment mode enabled.',
    tags: ['smoke', 'regression', 'sales', 'pos', 'payment'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Sales / POS screen', expected_result: 'POS opens with empty cart' },
      { description: 'Search and add "Biscuit" qty: 3', expected_result: 'Cart shows Biscuit x3, subtotal calculated' },
      { description: 'Tap "Checkout" and select payment: Cash, enter ₹100 tendered', expected_result: 'Change amount shown: ₹100 - invoice total' },
      { description: 'Tap "Confirm Payment"', expected_result: 'Invoice generated. Stock reduced. Cash drawer opens (if configured).' },
    ],
  },
  {
    title: 'Create sale with multiple products and UPI payment',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'UPI payment mode enabled. At least 3 products in stock.',
    tags: ['smoke', 'regression', 'sales', 'upi', 'payment'],
    is_regression: true,
    steps: [
      { description: 'Add 3 different products to POS cart', expected_result: 'Cart shows 3 line items with subtotals' },
      { description: 'Tap Checkout, select UPI payment', expected_result: 'UPI QR code displayed or UPI ID field shown' },
      { description: 'Mark payment as received', expected_result: 'Invoice created with UPI as payment mode' },
    ],
  },
  {
    title: 'Apply item-level discount on POS',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Product in cart. Discount allowed for this product.',
    tags: ['sales', 'discount', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Add product to cart at ₹200', expected_result: 'Cart shows ₹200' },
      { description: 'Tap product row > Edit > Discount: 10%', expected_result: 'Discount ₹20 applied. Line item shows ₹180.' },
      { description: 'Confirm checkout', expected_result: 'Invoice shows item discount and final total correctly' },
    ],
  },
  {
    title: 'Apply invoice-level discount percentage',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Items in cart. Total before discount: ₹1000.',
    tags: ['sales', 'discount', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On checkout screen, enter Invoice Discount: 5%', expected_result: '₹50 discount applied. Total shows ₹950.' },
      { description: 'Confirm sale', expected_result: 'Invoice records both item subtotal and invoice-level discount separately' },
    ],
  },
  {
    title: 'Customer linked to sale tracks purchase history',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer "Ravi Kumar" exists. POS open.',
    tags: ['sales', 'customers', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search and select customer "Ravi Kumar" in POS', expected_result: 'Customer linked to sale' },
      { description: 'Complete the sale', expected_result: 'Invoice generated with customer name. Sale visible in Ravi Kumar\'s purchase history.' },
    ],
  },
  {
    title: 'Sale invoice PDF is generated and shareable',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'A completed sale exists.',
    tags: ['sales', 'invoice', 'pdf', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open completed sale and tap "Download Invoice"', expected_result: 'PDF generated with all sale details' },
      { description: 'Tap "Share"', expected_result: 'Android share sheet opens. Invoice can be shared via WhatsApp, email, etc.' },
    ],
  },
  {
    title: 'Sale return (credit note) restores stock and records refund',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 7,
    is_automation_ready: false,
    preconditions: 'Completed invoice exists. Customer wants to return 2 units.',
    tags: ['sales', 'return', 'credit-note', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open invoice > tap "Return Items"', expected_result: 'Return form shows items from invoice' },
      { description: 'Select 2 units to return, reason: "Damaged product"', expected_result: 'Return amount calculated' },
      { description: 'Confirm return', expected_result: 'Stock restored by 2 units. Credit note created. Refund record added to customer account.' },
    ],
  },
  {
    title: 'Barcode scan adds product to POS cart',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: false,
    preconditions: 'Product has barcode registered. Physical barcode scanner connected or camera available.',
    tags: ['sales', 'barcode', 'pos', 'regression'],
    is_regression: true,
    steps: [
      { description: 'In POS, activate barcode scan mode', expected_result: 'Camera opens' },
      { description: 'Scan product barcode', expected_result: 'Product added to cart automatically with qty 1. Scan again increments qty.' },
    ],
  },
  {
    title: 'Hold sale and resume from held sales list',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Items in POS cart.',
    tags: ['sales', 'hold', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap "Hold Sale" with 3 items in cart', expected_result: 'Sale saved to held list. Cart clears.' },
      { description: 'Add different items for another customer and complete sale', expected_result: 'New sale completes independently' },
      { description: 'Access "Held Sales" and retrieve first sale', expected_result: 'Original cart with 3 items restored. Can complete checkout.' },
    ],
  },
  {
    title: 'Split payment between cash and card',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Cash and Card payment modes enabled. Invoice total: ₹500.',
    tags: ['sales', 'payment', 'split', 'regression'],
    is_regression: true,
    steps: [
      { description: 'On checkout, select "Split Payment"', expected_result: 'Split payment interface shows with multiple payment mode rows' },
      { description: 'Enter Cash: ₹300, Card: ₹200', expected_result: 'Total shows ₹500 matched. No outstanding balance.' },
      { description: 'Confirm payment', expected_result: 'Invoice records both payment modes and amounts' },
    ],
  },
  {
    title: 'Credit sale records outstanding balance against customer',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: true,
    preconditions: 'Customer "Priya Sharma" has credit limit ₹5,000. Current outstanding ₹0.',
    tags: ['sales', 'credit', 'customers', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create sale for Priya Sharma, total ₹1,200, payment mode: Credit', expected_result: 'Sale saved. Customer outstanding now shows ₹1,200.' },
      { description: 'Check customer ledger', expected_result: 'Ledger entry shows Invoice date, amount ₹1,200, status Outstanding' },
    ],
  },
  {
    title: 'GST invoice shows CGST + SGST split for intrastate sale',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Business and customer in same state. Product GST = 18%.',
    tags: ['sales', 'gst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create intrastate sale for a product priced ₹100 + 18% GST', expected_result: 'Invoice shows CGST 9% = ₹9, SGST 9% = ₹9, Total = ₹118' },
    ],
  },
  {
    title: 'GST invoice shows IGST for interstate sale',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer state differs from business state. Product GST = 18%.',
    tags: ['sales', 'gst', 'igst', 'invoice', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create interstate sale for product ₹100 + 18% GST', expected_result: 'Invoice shows IGST 18% = ₹18, Total = ₹118 (no CGST/SGST split)' },
    ],
  },
  {
    title: 'Daily sales summary totals match individual invoice sum',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Multiple completed sales today.',
    tags: ['sales', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Sales > Today\'s Summary', expected_result: 'Summary shows total sales amount' },
      { description: 'Verify by summing all today\'s completed invoices', expected_result: 'Summary total matches manual sum of all today\'s invoices' },
    ],
  },
  {
    title: 'Sale with quantity 0 is rejected',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Product in POS cart.',
    tags: ['sales', 'negative', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Set product quantity to 0 in cart', expected_result: 'Product is removed from cart OR error "Quantity must be at least 1" shown' },
    ],
  },
  {
    title: 'Discount greater than allowed maximum is blocked',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product has max discount configured as 15%.',
    tags: ['sales', 'discount', 'negative', 'validation'],
    is_regression: false,
    steps: [
      { description: 'Try to apply 20% discount on product with 15% max', expected_result: 'Error: "Maximum discount for this product is 15%. Staff cannot apply higher discount without manager approval."' },
    ],
  },
  {
    title: 'Pending payment invoice appears in outstanding report',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Credit sale made to customer.',
    tags: ['sales', 'credit', 'reports', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Reports > Outstanding Payments', expected_result: 'Customer with credit sale appears with outstanding amount' },
    ],
  },
  {
    title: 'Partial payment records remaining balance',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Invoice total ₹1,000.',
    tags: ['sales', 'payment', 'partial', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Checkout with partial payment: ₹600 cash', expected_result: 'Invoice saved with status "Partially Paid". Outstanding balance: ₹400 recorded.' },
    ],
  },
  {
    title: 'Duplicate invoice number cannot be created',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Invoice INV-2025-0042 already exists.',
    tags: ['sales', 'invoice', 'negative', 'duplicate'],
    is_regression: false,
    steps: [
      { description: 'Attempt to save new invoice with manual number INV-2025-0042', expected_result: 'Error: "Invoice number already exists. Please use a unique number."' },
    ],
  },
  {
    title: 'Invoice numbering auto-increments correctly',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Auto invoice numbering enabled. Last invoice: INV-2025-0099.',
    tags: ['sales', 'invoice', 'numbering', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create new sale and complete payment', expected_result: 'Invoice number assigned as INV-2025-0100 automatically' },
    ],
  },
  {
    title: 'Sale search by invoice number returns exact match',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 3,
    is_automation_ready: true,
    preconditions: 'Invoice INV-2025-0042 exists.',
    tags: ['sales', 'search', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Search "INV-2025-0042" in Sales list', expected_result: 'Only that invoice is shown in results' },
    ],
  },
  {
    title: 'POS works offline and queues sale for sync',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'App has offline data. Device internet disabled.',
    tags: ['sales', 'offline', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Complete a sale while offline', expected_result: 'Sale saved locally. Invoice generated. Stock decremented in local DB.' },
      { description: 'Restore internet', expected_result: 'Sale syncs to server. Server invoice matches local. No duplicate created.' },
    ],
  },
  {
    title: 'Loyalty points awarded on sale completion',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Loyalty program enabled. Customer "Anil Singh" enrolled. Rule: 1 point per ₹10.',
    tags: ['sales', 'loyalty', 'customers'],
    is_regression: false,
    steps: [
      { description: 'Complete ₹500 sale for Anil Singh', expected_result: 'Customer earns 50 loyalty points. Points visible in customer profile.' },
    ],
  },
  {
    title: 'POS session open/close tracks daily cash float',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'POS session management enabled.',
    tags: ['sales', 'pos', 'session', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open POS session with opening float: ₹1,000', expected_result: 'Session started. Opening balance recorded.' },
      { description: 'Complete ₹800 cash sale', expected_result: 'Expected closing balance: ₹1,800' },
      { description: 'Close POS session', expected_result: 'Summary shows Opening: ₹1,000, Cash Sales: ₹800, Expected Closing: ₹1,800' },
    ],
  },
  {
    title: 'Thermal printer prints invoice on sale confirmation',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Bluetooth thermal printer paired. Auto-print on sale enabled.',
    tags: ['sales', 'printing', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Complete a sale', expected_result: 'Invoice automatically sent to paired thermal printer. Physical receipt printed within 5 seconds.' },
    ],
  },
  {
    title: 'Sale with GST-exempt product shows zero GST',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 4,
    is_automation_ready: true,
    preconditions: 'Product "Unbranded Rice" has GST 0%.',
    tags: ['sales', 'gst', 'exempt'],
    is_regression: false,
    steps: [
      { description: 'Add GST-exempt product to sale', expected_result: 'Cart shows ₹0 GST for that product' },
      { description: 'Invoice generated', expected_result: 'Invoice shows GST amount as ₹0.00 for exempt product' },
    ],
  },
  {
    title: 'Cart persists after app backgrounded and foregrounded',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Items in POS cart.',
    tags: ['sales', 'pos', 'session', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Add 3 items to POS cart', expected_result: 'Cart shows 3 items' },
      { description: 'Press home button (background app) and return after 2 minutes', expected_result: 'POS screen shows same 3 items in cart. No data lost.' },
    ],
  },
  {
    title: 'Network failure during payment does not duplicate invoice',
    module: 'Sales',
    priority: 'critical',
    estimated_minutes: 8,
    is_automation_ready: false,
    preconditions: 'Items in cart, about to confirm payment.',
    tags: ['sales', 'negative', 'network', 'data-integrity', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Tap Confirm Payment', expected_result: 'App initiates save request' },
      { description: 'Simulate network loss immediately after tap', expected_result: 'App shows retry option or error message' },
      { description: 'Restore network and retry', expected_result: 'Invoice created exactly once. No duplicate invoice on server.' },
    ],
  },
  {
    title: 'Sales report filtered by date range is accurate',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Sales data across multiple dates.',
    tags: ['sales', 'reports', 'filter', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Navigate to Sales > Report > Set date range: 1st–7th of this month', expected_result: 'Report shows only sales within that range' },
      { description: 'Verify total matches sum of invoices in range', expected_result: 'Total is accurate' },
    ],
  },
  {
    title: 'Sales list pagination works correctly with 1000+ invoices',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'Database has 1000+ invoices.',
    tags: ['sales', 'performance', 'pagination', 'edge-case'],
    is_regression: false,
    steps: [
      { description: 'Navigate to Sales list with 1000+ invoices', expected_result: 'List loads quickly with pagination or infinite scroll' },
      { description: 'Scroll to bottom', expected_result: 'Next page loads without crash. All invoices accessible.' },
    ],
  },
  {
    title: 'Customer\'s credit limit prevents sale when exceeded',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 5,
    is_automation_ready: true,
    preconditions: 'Customer "Suresh" has credit limit ₹2,000, current outstanding ₹1,800.',
    tags: ['sales', 'credit', 'negative', 'validation', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Create credit sale for Suresh, total ₹500', expected_result: 'Warning: "Credit limit exceeded. Outstanding: ₹1,800, Limit: ₹2,000, New Total would be: ₹2,300. Proceed?"' },
      { description: 'Attempt to confirm without manager override', expected_result: 'Sale blocked. Staff cannot override without manager PIN.' },
    ],
  },
  {
    title: 'Void invoice removes it from reports and restores stock',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 6,
    is_automation_ready: false,
    preconditions: 'Completed invoice exists. Manager role logged in.',
    tags: ['sales', 'void', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Open invoice and tap "Void Invoice"', expected_result: 'Confirmation: "Void this invoice? Stock will be restored and sale removed from reports."' },
      { description: 'Enter manager PIN and confirm', expected_result: 'Invoice voided. Stock restored. Invoice marked VOID. Removed from revenue reports.' },
    ],
  },
  {
    title: 'Multiple concurrent sales on different devices do not conflict',
    module: 'Sales',
    priority: 'high',
    estimated_minutes: 10,
    is_automation_ready: false,
    preconditions: 'Two devices logged in to same account. Both on POS screen.',
    tags: ['sales', 'concurrency', 'edge-case', 'regression'],
    is_regression: true,
    steps: [
      { description: 'Device A and Device B both start a sale at same time for same product', expected_result: 'Both sales process independently' },
      { description: 'Both complete payment', expected_result: 'Both invoices created with unique invoice numbers. Stock correctly reduced for both.' },
    ],
  },
  {
    title: 'WhatsApp invoice sharing sends correct PDF',
    module: 'Sales',
    priority: 'medium',
    estimated_minutes: 5,
    is_automation_ready: false,
    preconditions: 'WhatsApp installed. Sale completed.',
    tags: ['sales', 'sharing', 'whatsapp'],
    is_regression: false,
    steps: [
      { description: 'Open invoice and tap "Share via WhatsApp"', expected_result: 'WhatsApp contact picker opens' },
      { description: 'Select a contact', expected_result: 'WhatsApp opens with invoice PDF attached and default message pre-filled' },
    ],
  },
];
